/*
 * Binance Spot REST API
 * OpenAPI Specifications for the Binance Spot REST API  API documents:   - [Github rest-api documentation file](https://github.com/binance/binance-spot-api-docs/blob/master/rest-api.md)   - [General API information for rest-api on website](https://developers.binance.com/docs/binance-spot-api-docs/rest-api/general-api-information)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.client.spot.websocket.api.market;

import com.binance.connector.client.common.configuration.SignatureConfiguration;
import com.binance.connector.client.common.websocket.configuration.WebSocketClientConfiguration;
import com.binance.connector.client.spot.websocket.api.SpotWebSocketApiUtil;
import com.binance.connector.client.spot.websocket.api.api.SpotWebSocketApi;
import com.binance.connector.client.spot.websocket.api.model.TradesAggregateRequest;
import com.binance.connector.client.spot.websocket.api.model.TradesAggregateResponse;
import java.util.concurrent.CompletableFuture;

/** API examples for MarketApi */
public class TradesAggregateExample {
    private SpotWebSocketApi api;

    public SpotWebSocketApi getApi() {
        if (api == null) {
            WebSocketClientConfiguration clientConfiguration =
                    SpotWebSocketApiUtil.getClientConfiguration();
            clientConfiguration.setAutoLogon(false);
            SignatureConfiguration signatureConfiguration = new SignatureConfiguration();
            signatureConfiguration.setApiKey("apiKey");
            signatureConfiguration.setPrivateKey("/path/to/private.key");
            clientConfiguration.setSignatureConfiguration(signatureConfiguration);
            api = new SpotWebSocketApi(clientConfiguration);
        }
        return api;
    }

    /**
     * WebSocket Aggregate trades
     *
     * <p>Get aggregate trades. An *aggregate trade* (aggtrade) represents one or more individual
     * trades. Trades that fill at the same time, from the same taker order, with the same price –
     * those trades are collected into an aggregate trade with total quantity of the individual
     * trades. If you need access to real-time trading activity, please consider using WebSocket
     * Streams: * &#x60;&lt;symbol&gt;@aggTrade&#x60; If you need historical aggregate trade data,
     * please consider using
     * [data.binance.vision](https://github.com/binance/binance-public-data/#aggtrades). Weight: 4
     */
    public void tradesAggregateExampleAsync() {
        TradesAggregateRequest tradesAggregateRequest = new TradesAggregateRequest();
        tradesAggregateRequest.symbol("BNBUSDT");
        CompletableFuture<TradesAggregateResponse> future =
                getApi().tradesAggregate(tradesAggregateRequest);
        future.handle(
                (response, error) -> {
                    if (error != null) {
                        System.err.println(error);
                    }
                    System.out.println(response);
                    return response;
                });
    }

    /**
     * WebSocket Aggregate trades
     *
     * <p>Get aggregate trades. An *aggregate trade* (aggtrade) represents one or more individual
     * trades. Trades that fill at the same time, from the same taker order, with the same price –
     * those trades are collected into an aggregate trade with total quantity of the individual
     * trades. If you need access to real-time trading activity, please consider using WebSocket
     * Streams: * &#x60;&lt;symbol&gt;@aggTrade&#x60; If you need historical aggregate trade data,
     * please consider using
     * [data.binance.vision](https://github.com/binance/binance-public-data/#aggtrades). Weight: 4
     */
    public void tradesAggregateExampleSync() {
        TradesAggregateRequest tradesAggregateRequest = new TradesAggregateRequest();
        tradesAggregateRequest.symbol("BNBUSDT");
        CompletableFuture<TradesAggregateResponse> future =
                getApi().tradesAggregate(tradesAggregateRequest);
        TradesAggregateResponse response = future.join();
        System.out.println(response);
    }
}
