/*
 * Binance Spot REST API
 * OpenAPI Specifications for the Binance Spot REST API  API documents:   - [Github rest-api documentation file](https://github.com/binance/binance-spot-api-docs/blob/master/rest-api.md)   - [General API information for rest-api on website](https://developers.binance.com/docs/binance-spot-api-docs/rest-api/general-api-information)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.client.spot.rest.model;

import com.binance.connector.client.spot.rest.JSON;
import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashSet;
import java.util.List;
import java.util.Objects;
import java.util.stream.Collectors;
import org.hibernate.validator.constraints.*;

/** ExecutionRulesResponse */
@jakarta.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.12.0")
public class ExecutionRulesResponse {
    public static final String SERIALIZED_NAME_SYMBOL_RULES = "symbolRules";

    @SerializedName(SERIALIZED_NAME_SYMBOL_RULES)
    @jakarta.annotation.Nullable
    private List<@Valid ExecutionRulesResponseSymbolRulesInner> symbolRules;

    public ExecutionRulesResponse() {}

    public ExecutionRulesResponse symbolRules(
            @jakarta.annotation.Nullable
                    List<@Valid ExecutionRulesResponseSymbolRulesInner> symbolRules) {
        this.symbolRules = symbolRules;
        return this;
    }

    public ExecutionRulesResponse addSymbolRulesItem(
            ExecutionRulesResponseSymbolRulesInner symbolRulesItem) {
        if (this.symbolRules == null) {
            this.symbolRules = new ArrayList<>();
        }
        this.symbolRules.add(symbolRulesItem);
        return this;
    }

    /**
     * Get symbolRules
     *
     * @return symbolRules
     */
    @jakarta.annotation.Nullable
    @Valid
    public List<@Valid ExecutionRulesResponseSymbolRulesInner> getSymbolRules() {
        return symbolRules;
    }

    public void setSymbolRules(
            @jakarta.annotation.Nullable
                    List<@Valid ExecutionRulesResponseSymbolRulesInner> symbolRules) {
        this.symbolRules = symbolRules;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ExecutionRulesResponse executionRulesResponse = (ExecutionRulesResponse) o;
        return Objects.equals(this.symbolRules, executionRulesResponse.symbolRules);
    }

    @Override
    public int hashCode() {
        return Objects.hash(symbolRules);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ExecutionRulesResponse {\n");
        sb.append("		symbolRules: ").append(toIndentedString(symbolRules)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    public String toUrlQueryString() {
        StringBuilder sb = new StringBuilder();

        Object symbolRulesValue = getSymbolRules();
        String symbolRulesValueAsString = "";
        symbolRulesValueAsString =
                (String)
                        ((Collection) symbolRulesValue)
                                .stream().map(Object::toString).collect(Collectors.joining(","));
        sb.append("symbolRules=").append(urlEncode(symbolRulesValueAsString)).append("");
        return sb.toString();
    }

    public static String urlEncode(String s) {
        try {
            return URLEncoder.encode(s, StandardCharsets.UTF_8.name());
        } catch (UnsupportedEncodingException e) {
            throw new RuntimeException(StandardCharsets.UTF_8.name() + " is unsupported", e);
        }
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n		");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("symbolRules");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to ExecutionRulesResponse
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!ExecutionRulesResponse.openapiRequiredFields
                    .isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(
                        String.format(
                                "The required field(s) %s in ExecutionRulesResponse is not found in"
                                        + " the empty JSON string",
                                ExecutionRulesResponse.openapiRequiredFields.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if (jsonObj.get("symbolRules") != null && !jsonObj.get("symbolRules").isJsonNull()) {
            JsonArray jsonArraysymbolRules = jsonObj.getAsJsonArray("symbolRules");
            if (jsonArraysymbolRules != null) {
                // ensure the json data is an array
                if (!jsonObj.get("symbolRules").isJsonArray()) {
                    throw new IllegalArgumentException(
                            String.format(
                                    "Expected the field `symbolRules` to be an array in the JSON"
                                            + " string but got `%s`",
                                    jsonObj.get("symbolRules").toString()));
                }

                // validate the optional field `symbolRules` (array)
                for (int i = 0; i < jsonArraysymbolRules.size(); i++) {
                    ExecutionRulesResponseSymbolRulesInner.validateJsonElement(
                            jsonArraysymbolRules.get(i));
                }
                ;
            }
        }
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!ExecutionRulesResponse.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'ExecutionRulesResponse' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<ExecutionRulesResponse> thisAdapter =
                    gson.getDelegateAdapter(this, TypeToken.get(ExecutionRulesResponse.class));

            return (TypeAdapter<T>)
                    new TypeAdapter<ExecutionRulesResponse>() {
                        @Override
                        public void write(JsonWriter out, ExecutionRulesResponse value)
                                throws IOException {
                            JsonElement obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                            elementAdapter.write(out, obj);
                        }

                        @Override
                        public ExecutionRulesResponse read(JsonReader in) throws IOException {
                            JsonElement jsonElement = elementAdapter.read(in);
                            // validateJsonElement(jsonElement);
                            return thisAdapter.fromJsonTree(jsonElement);
                        }
                    }.nullSafe();
        }
    }

    /**
     * Create an instance of ExecutionRulesResponse given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of ExecutionRulesResponse
     * @throws IOException if the JSON string is invalid with respect to ExecutionRulesResponse
     */
    public static ExecutionRulesResponse fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, ExecutionRulesResponse.class);
    }

    /**
     * Convert an instance of ExecutionRulesResponse to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
