/*
 * Binance Simple Earn REST API
 * OpenAPI Specification for the Binance Simple Earn REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.client.simple_earn.rest.model;

import com.binance.connector.client.simple_earn.rest.JSON;
import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import jakarta.validation.constraints.*;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.HashSet;
import java.util.Objects;
import org.hibernate.validator.constraints.*;

/** GetBfusdQuotaDetailsResponseFastRedemptionQuota */
@jakarta.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.12.0")
public class GetBfusdQuotaDetailsResponseFastRedemptionQuota {
    public static final String SERIALIZED_NAME_LEFT_QUOTA = "leftQuota";

    @SerializedName(SERIALIZED_NAME_LEFT_QUOTA)
    @jakarta.annotation.Nullable
    private String leftQuota;

    public static final String SERIALIZED_NAME_MINIMUM = "minimum";

    @SerializedName(SERIALIZED_NAME_MINIMUM)
    @jakarta.annotation.Nullable
    private String minimum;

    public static final String SERIALIZED_NAME_FEE = "fee";

    @SerializedName(SERIALIZED_NAME_FEE)
    @jakarta.annotation.Nullable
    private String fee;

    public static final String SERIALIZED_NAME_FREE_QUOTA = "freeQuota";

    @SerializedName(SERIALIZED_NAME_FREE_QUOTA)
    @jakarta.annotation.Nullable
    private String freeQuota;

    public GetBfusdQuotaDetailsResponseFastRedemptionQuota() {}

    public GetBfusdQuotaDetailsResponseFastRedemptionQuota leftQuota(
            @jakarta.annotation.Nullable String leftQuota) {
        this.leftQuota = leftQuota;
        return this;
    }

    /**
     * Get leftQuota
     *
     * @return leftQuota
     */
    @jakarta.annotation.Nullable
    public String getLeftQuota() {
        return leftQuota;
    }

    public void setLeftQuota(@jakarta.annotation.Nullable String leftQuota) {
        this.leftQuota = leftQuota;
    }

    public GetBfusdQuotaDetailsResponseFastRedemptionQuota minimum(
            @jakarta.annotation.Nullable String minimum) {
        this.minimum = minimum;
        return this;
    }

    /**
     * Get minimum
     *
     * @return minimum
     */
    @jakarta.annotation.Nullable
    public String getMinimum() {
        return minimum;
    }

    public void setMinimum(@jakarta.annotation.Nullable String minimum) {
        this.minimum = minimum;
    }

    public GetBfusdQuotaDetailsResponseFastRedemptionQuota fee(
            @jakarta.annotation.Nullable String fee) {
        this.fee = fee;
        return this;
    }

    /**
     * Get fee
     *
     * @return fee
     */
    @jakarta.annotation.Nullable
    public String getFee() {
        return fee;
    }

    public void setFee(@jakarta.annotation.Nullable String fee) {
        this.fee = fee;
    }

    public GetBfusdQuotaDetailsResponseFastRedemptionQuota freeQuota(
            @jakarta.annotation.Nullable String freeQuota) {
        this.freeQuota = freeQuota;
        return this;
    }

    /**
     * Get freeQuota
     *
     * @return freeQuota
     */
    @jakarta.annotation.Nullable
    public String getFreeQuota() {
        return freeQuota;
    }

    public void setFreeQuota(@jakarta.annotation.Nullable String freeQuota) {
        this.freeQuota = freeQuota;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetBfusdQuotaDetailsResponseFastRedemptionQuota
                getBfusdQuotaDetailsResponseFastRedemptionQuota =
                        (GetBfusdQuotaDetailsResponseFastRedemptionQuota) o;
        return Objects.equals(
                        this.leftQuota, getBfusdQuotaDetailsResponseFastRedemptionQuota.leftQuota)
                && Objects.equals(
                        this.minimum, getBfusdQuotaDetailsResponseFastRedemptionQuota.minimum)
                && Objects.equals(this.fee, getBfusdQuotaDetailsResponseFastRedemptionQuota.fee)
                && Objects.equals(
                        this.freeQuota, getBfusdQuotaDetailsResponseFastRedemptionQuota.freeQuota);
    }

    @Override
    public int hashCode() {
        return Objects.hash(leftQuota, minimum, fee, freeQuota);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class GetBfusdQuotaDetailsResponseFastRedemptionQuota {\n");
        sb.append("		leftQuota: ").append(toIndentedString(leftQuota)).append("\n");
        sb.append("		minimum: ").append(toIndentedString(minimum)).append("\n");
        sb.append("		fee: ").append(toIndentedString(fee)).append("\n");
        sb.append("		freeQuota: ").append(toIndentedString(freeQuota)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    public String toUrlQueryString() {
        StringBuilder sb = new StringBuilder();

        Object leftQuotaValue = getLeftQuota();
        String leftQuotaValueAsString = "";
        leftQuotaValueAsString = leftQuotaValue.toString();
        sb.append("leftQuota=").append(urlEncode(leftQuotaValueAsString)).append("");
        Object minimumValue = getMinimum();
        String minimumValueAsString = "";
        minimumValueAsString = minimumValue.toString();
        sb.append("minimum=").append(urlEncode(minimumValueAsString)).append("");
        Object feeValue = getFee();
        String feeValueAsString = "";
        feeValueAsString = feeValue.toString();
        sb.append("fee=").append(urlEncode(feeValueAsString)).append("");
        Object freeQuotaValue = getFreeQuota();
        String freeQuotaValueAsString = "";
        freeQuotaValueAsString = freeQuotaValue.toString();
        sb.append("freeQuota=").append(urlEncode(freeQuotaValueAsString)).append("");
        return sb.toString();
    }

    public static String urlEncode(String s) {
        try {
            return URLEncoder.encode(s, StandardCharsets.UTF_8.name());
        } catch (UnsupportedEncodingException e) {
            throw new RuntimeException(StandardCharsets.UTF_8.name() + " is unsupported", e);
        }
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n		");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("leftQuota");
        openapiFields.add("minimum");
        openapiFields.add("fee");
        openapiFields.add("freeQuota");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to
     *     GetBfusdQuotaDetailsResponseFastRedemptionQuota
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!GetBfusdQuotaDetailsResponseFastRedemptionQuota.openapiRequiredFields
                    .isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(
                        String.format(
                                "The required field(s) %s in"
                                        + " GetBfusdQuotaDetailsResponseFastRedemptionQuota is not"
                                        + " found in the empty JSON string",
                                GetBfusdQuotaDetailsResponseFastRedemptionQuota
                                        .openapiRequiredFields
                                        .toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if ((jsonObj.get("leftQuota") != null && !jsonObj.get("leftQuota").isJsonNull())
                && !jsonObj.get("leftQuota").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `leftQuota` to be a primitive type in the JSON"
                                    + " string but got `%s`",
                            jsonObj.get("leftQuota").toString()));
        }
        if ((jsonObj.get("minimum") != null && !jsonObj.get("minimum").isJsonNull())
                && !jsonObj.get("minimum").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `minimum` to be a primitive type in the JSON string"
                                    + " but got `%s`",
                            jsonObj.get("minimum").toString()));
        }
        if ((jsonObj.get("fee") != null && !jsonObj.get("fee").isJsonNull())
                && !jsonObj.get("fee").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `fee` to be a primitive type in the JSON string but"
                                    + " got `%s`",
                            jsonObj.get("fee").toString()));
        }
        if ((jsonObj.get("freeQuota") != null && !jsonObj.get("freeQuota").isJsonNull())
                && !jsonObj.get("freeQuota").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `freeQuota` to be a primitive type in the JSON"
                                    + " string but got `%s`",
                            jsonObj.get("freeQuota").toString()));
        }
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!GetBfusdQuotaDetailsResponseFastRedemptionQuota.class.isAssignableFrom(
                    type.getRawType())) {
                return null; // this class only serializes
                // 'GetBfusdQuotaDetailsResponseFastRedemptionQuota' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<GetBfusdQuotaDetailsResponseFastRedemptionQuota> thisAdapter =
                    gson.getDelegateAdapter(
                            this,
                            TypeToken.get(GetBfusdQuotaDetailsResponseFastRedemptionQuota.class));

            return (TypeAdapter<T>)
                    new TypeAdapter<GetBfusdQuotaDetailsResponseFastRedemptionQuota>() {
                        @Override
                        public void write(
                                JsonWriter out,
                                GetBfusdQuotaDetailsResponseFastRedemptionQuota value)
                                throws IOException {
                            JsonElement obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                            elementAdapter.write(out, obj);
                        }

                        @Override
                        public GetBfusdQuotaDetailsResponseFastRedemptionQuota read(JsonReader in)
                                throws IOException {
                            JsonElement jsonElement = elementAdapter.read(in);
                            // validateJsonElement(jsonElement);
                            return thisAdapter.fromJsonTree(jsonElement);
                        }
                    }.nullSafe();
        }
    }

    /**
     * Create an instance of GetBfusdQuotaDetailsResponseFastRedemptionQuota given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of GetBfusdQuotaDetailsResponseFastRedemptionQuota
     * @throws IOException if the JSON string is invalid with respect to
     *     GetBfusdQuotaDetailsResponseFastRedemptionQuota
     */
    public static GetBfusdQuotaDetailsResponseFastRedemptionQuota fromJson(String jsonString)
            throws IOException {
        return JSON.getGson()
                .fromJson(jsonString, GetBfusdQuotaDetailsResponseFastRedemptionQuota.class);
    }

    /**
     * Convert an instance of GetBfusdQuotaDetailsResponseFastRedemptionQuota to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
