/*
 * Binance Simple Earn REST API
 * OpenAPI Specification for the Binance Simple Earn REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.client.simple_earn.rest.model;

import com.binance.connector.client.simple_earn.rest.JSON;
import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import jakarta.validation.constraints.*;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.HashSet;
import java.util.Objects;
import org.hibernate.validator.constraints.*;

/** GetRwusdRewardsHistoryResponseRowsInner */
@jakarta.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.12.0")
public class GetRwusdRewardsHistoryResponseRowsInner {
    public static final String SERIALIZED_NAME_TIME = "time";

    @SerializedName(SERIALIZED_NAME_TIME)
    @jakarta.annotation.Nullable
    private Long time;

    public static final String SERIALIZED_NAME_REWARDS_AMOUNT = "rewardsAmount";

    @SerializedName(SERIALIZED_NAME_REWARDS_AMOUNT)
    @jakarta.annotation.Nullable
    private String rewardsAmount;

    public static final String SERIALIZED_NAME_RWUSD_POSITION = "rwusdPosition";

    @SerializedName(SERIALIZED_NAME_RWUSD_POSITION)
    @jakarta.annotation.Nullable
    private String rwusdPosition;

    public static final String SERIALIZED_NAME_ANNUAL_PERCENTAGE_RATE = "annualPercentageRate";

    @SerializedName(SERIALIZED_NAME_ANNUAL_PERCENTAGE_RATE)
    @jakarta.annotation.Nullable
    private String annualPercentageRate;

    public GetRwusdRewardsHistoryResponseRowsInner() {}

    public GetRwusdRewardsHistoryResponseRowsInner time(@jakarta.annotation.Nullable Long time) {
        this.time = time;
        return this;
    }

    /**
     * Get time
     *
     * @return time
     */
    @jakarta.annotation.Nullable
    public Long getTime() {
        return time;
    }

    public void setTime(@jakarta.annotation.Nullable Long time) {
        this.time = time;
    }

    public GetRwusdRewardsHistoryResponseRowsInner rewardsAmount(
            @jakarta.annotation.Nullable String rewardsAmount) {
        this.rewardsAmount = rewardsAmount;
        return this;
    }

    /**
     * Get rewardsAmount
     *
     * @return rewardsAmount
     */
    @jakarta.annotation.Nullable
    public String getRewardsAmount() {
        return rewardsAmount;
    }

    public void setRewardsAmount(@jakarta.annotation.Nullable String rewardsAmount) {
        this.rewardsAmount = rewardsAmount;
    }

    public GetRwusdRewardsHistoryResponseRowsInner rwusdPosition(
            @jakarta.annotation.Nullable String rwusdPosition) {
        this.rwusdPosition = rwusdPosition;
        return this;
    }

    /**
     * Get rwusdPosition
     *
     * @return rwusdPosition
     */
    @jakarta.annotation.Nullable
    public String getRwusdPosition() {
        return rwusdPosition;
    }

    public void setRwusdPosition(@jakarta.annotation.Nullable String rwusdPosition) {
        this.rwusdPosition = rwusdPosition;
    }

    public GetRwusdRewardsHistoryResponseRowsInner annualPercentageRate(
            @jakarta.annotation.Nullable String annualPercentageRate) {
        this.annualPercentageRate = annualPercentageRate;
        return this;
    }

    /**
     * Get annualPercentageRate
     *
     * @return annualPercentageRate
     */
    @jakarta.annotation.Nullable
    public String getAnnualPercentageRate() {
        return annualPercentageRate;
    }

    public void setAnnualPercentageRate(@jakarta.annotation.Nullable String annualPercentageRate) {
        this.annualPercentageRate = annualPercentageRate;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetRwusdRewardsHistoryResponseRowsInner getRwusdRewardsHistoryResponseRowsInner =
                (GetRwusdRewardsHistoryResponseRowsInner) o;
        return Objects.equals(this.time, getRwusdRewardsHistoryResponseRowsInner.time)
                && Objects.equals(
                        this.rewardsAmount, getRwusdRewardsHistoryResponseRowsInner.rewardsAmount)
                && Objects.equals(
                        this.rwusdPosition, getRwusdRewardsHistoryResponseRowsInner.rwusdPosition)
                && Objects.equals(
                        this.annualPercentageRate,
                        getRwusdRewardsHistoryResponseRowsInner.annualPercentageRate);
    }

    @Override
    public int hashCode() {
        return Objects.hash(time, rewardsAmount, rwusdPosition, annualPercentageRate);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class GetRwusdRewardsHistoryResponseRowsInner {\n");
        sb.append("		time: ").append(toIndentedString(time)).append("\n");
        sb.append("		rewardsAmount: ").append(toIndentedString(rewardsAmount)).append("\n");
        sb.append("		rwusdPosition: ").append(toIndentedString(rwusdPosition)).append("\n");
        sb.append("		annualPercentageRate: ")
                .append(toIndentedString(annualPercentageRate))
                .append("\n");
        sb.append("}");
        return sb.toString();
    }

    public String toUrlQueryString() {
        StringBuilder sb = new StringBuilder();

        Object timeValue = getTime();
        String timeValueAsString = "";
        timeValueAsString = timeValue.toString();
        sb.append("time=").append(urlEncode(timeValueAsString)).append("");
        Object rewardsAmountValue = getRewardsAmount();
        String rewardsAmountValueAsString = "";
        rewardsAmountValueAsString = rewardsAmountValue.toString();
        sb.append("rewardsAmount=").append(urlEncode(rewardsAmountValueAsString)).append("");
        Object rwusdPositionValue = getRwusdPosition();
        String rwusdPositionValueAsString = "";
        rwusdPositionValueAsString = rwusdPositionValue.toString();
        sb.append("rwusdPosition=").append(urlEncode(rwusdPositionValueAsString)).append("");
        Object annualPercentageRateValue = getAnnualPercentageRate();
        String annualPercentageRateValueAsString = "";
        annualPercentageRateValueAsString = annualPercentageRateValue.toString();
        sb.append("annualPercentageRate=")
                .append(urlEncode(annualPercentageRateValueAsString))
                .append("");
        return sb.toString();
    }

    public static String urlEncode(String s) {
        try {
            return URLEncoder.encode(s, StandardCharsets.UTF_8.name());
        } catch (UnsupportedEncodingException e) {
            throw new RuntimeException(StandardCharsets.UTF_8.name() + " is unsupported", e);
        }
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n		");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("time");
        openapiFields.add("rewardsAmount");
        openapiFields.add("rwusdPosition");
        openapiFields.add("annualPercentageRate");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to
     *     GetRwusdRewardsHistoryResponseRowsInner
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!GetRwusdRewardsHistoryResponseRowsInner.openapiRequiredFields
                    .isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(
                        String.format(
                                "The required field(s) %s in"
                                    + " GetRwusdRewardsHistoryResponseRowsInner is not found in the"
                                    + " empty JSON string",
                                GetRwusdRewardsHistoryResponseRowsInner.openapiRequiredFields
                                        .toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if ((jsonObj.get("rewardsAmount") != null && !jsonObj.get("rewardsAmount").isJsonNull())
                && !jsonObj.get("rewardsAmount").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `rewardsAmount` to be a primitive type in the JSON"
                                    + " string but got `%s`",
                            jsonObj.get("rewardsAmount").toString()));
        }
        if ((jsonObj.get("rwusdPosition") != null && !jsonObj.get("rwusdPosition").isJsonNull())
                && !jsonObj.get("rwusdPosition").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `rwusdPosition` to be a primitive type in the JSON"
                                    + " string but got `%s`",
                            jsonObj.get("rwusdPosition").toString()));
        }
        if ((jsonObj.get("annualPercentageRate") != null
                        && !jsonObj.get("annualPercentageRate").isJsonNull())
                && !jsonObj.get("annualPercentageRate").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `annualPercentageRate` to be a primitive type in"
                                    + " the JSON string but got `%s`",
                            jsonObj.get("annualPercentageRate").toString()));
        }
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!GetRwusdRewardsHistoryResponseRowsInner.class.isAssignableFrom(
                    type.getRawType())) {
                return null; // this class only serializes 'GetRwusdRewardsHistoryResponseRowsInner'
                // and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<GetRwusdRewardsHistoryResponseRowsInner> thisAdapter =
                    gson.getDelegateAdapter(
                            this, TypeToken.get(GetRwusdRewardsHistoryResponseRowsInner.class));

            return (TypeAdapter<T>)
                    new TypeAdapter<GetRwusdRewardsHistoryResponseRowsInner>() {
                        @Override
                        public void write(
                                JsonWriter out, GetRwusdRewardsHistoryResponseRowsInner value)
                                throws IOException {
                            JsonElement obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                            elementAdapter.write(out, obj);
                        }

                        @Override
                        public GetRwusdRewardsHistoryResponseRowsInner read(JsonReader in)
                                throws IOException {
                            JsonElement jsonElement = elementAdapter.read(in);
                            // validateJsonElement(jsonElement);
                            return thisAdapter.fromJsonTree(jsonElement);
                        }
                    }.nullSafe();
        }
    }

    /**
     * Create an instance of GetRwusdRewardsHistoryResponseRowsInner given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of GetRwusdRewardsHistoryResponseRowsInner
     * @throws IOException if the JSON string is invalid with respect to
     *     GetRwusdRewardsHistoryResponseRowsInner
     */
    public static GetRwusdRewardsHistoryResponseRowsInner fromJson(String jsonString)
            throws IOException {
        return JSON.getGson().fromJson(jsonString, GetRwusdRewardsHistoryResponseRowsInner.class);
    }

    /**
     * Convert an instance of GetRwusdRewardsHistoryResponseRowsInner to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
