/*
 * Binance Wallet REST API
 * OpenAPI Specification for the Binance Wallet REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.client.wallet.rest.model;

import com.binance.connector.client.wallet.rest.JSON;
import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import jakarta.validation.constraints.*;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.HashSet;
import java.util.Objects;
import org.hibernate.validator.constraints.*;

/** DailyAccountSnapshotResponseSnapshotVosInnerDataBalancesInner */
@jakarta.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.12.0")
public class DailyAccountSnapshotResponseSnapshotVosInnerDataBalancesInner {
    public static final String SERIALIZED_NAME_ASSET = "asset";

    @SerializedName(SERIALIZED_NAME_ASSET)
    @jakarta.annotation.Nullable
    private String asset;

    public static final String SERIALIZED_NAME_FREE = "free";

    @SerializedName(SERIALIZED_NAME_FREE)
    @jakarta.annotation.Nullable
    private String free;

    public static final String SERIALIZED_NAME_LOCKED = "locked";

    @SerializedName(SERIALIZED_NAME_LOCKED)
    @jakarta.annotation.Nullable
    private String locked;

    public DailyAccountSnapshotResponseSnapshotVosInnerDataBalancesInner() {}

    public DailyAccountSnapshotResponseSnapshotVosInnerDataBalancesInner asset(
            @jakarta.annotation.Nullable String asset) {
        this.asset = asset;
        return this;
    }

    /**
     * Get asset
     *
     * @return asset
     */
    @jakarta.annotation.Nullable
    public String getAsset() {
        return asset;
    }

    public void setAsset(@jakarta.annotation.Nullable String asset) {
        this.asset = asset;
    }

    public DailyAccountSnapshotResponseSnapshotVosInnerDataBalancesInner free(
            @jakarta.annotation.Nullable String free) {
        this.free = free;
        return this;
    }

    /**
     * Get free
     *
     * @return free
     */
    @jakarta.annotation.Nullable
    public String getFree() {
        return free;
    }

    public void setFree(@jakarta.annotation.Nullable String free) {
        this.free = free;
    }

    public DailyAccountSnapshotResponseSnapshotVosInnerDataBalancesInner locked(
            @jakarta.annotation.Nullable String locked) {
        this.locked = locked;
        return this;
    }

    /**
     * Get locked
     *
     * @return locked
     */
    @jakarta.annotation.Nullable
    public String getLocked() {
        return locked;
    }

    public void setLocked(@jakarta.annotation.Nullable String locked) {
        this.locked = locked;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DailyAccountSnapshotResponseSnapshotVosInnerDataBalancesInner
                dailyAccountSnapshotResponseSnapshotVosInnerDataBalancesInner =
                        (DailyAccountSnapshotResponseSnapshotVosInnerDataBalancesInner) o;
        return Objects.equals(
                        this.asset,
                        dailyAccountSnapshotResponseSnapshotVosInnerDataBalancesInner.asset)
                && Objects.equals(
                        this.free,
                        dailyAccountSnapshotResponseSnapshotVosInnerDataBalancesInner.free)
                && Objects.equals(
                        this.locked,
                        dailyAccountSnapshotResponseSnapshotVosInnerDataBalancesInner.locked);
    }

    @Override
    public int hashCode() {
        return Objects.hash(asset, free, locked);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class DailyAccountSnapshotResponseSnapshotVosInnerDataBalancesInner {\n");
        sb.append("		asset: ").append(toIndentedString(asset)).append("\n");
        sb.append("		free: ").append(toIndentedString(free)).append("\n");
        sb.append("		locked: ").append(toIndentedString(locked)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    public String toUrlQueryString() {
        StringBuilder sb = new StringBuilder();

        Object assetValue = getAsset();
        String assetValueAsString = "";
        assetValueAsString = assetValue.toString();
        sb.append("asset=").append(urlEncode(assetValueAsString)).append("");
        Object freeValue = getFree();
        String freeValueAsString = "";
        freeValueAsString = freeValue.toString();
        sb.append("free=").append(urlEncode(freeValueAsString)).append("");
        Object lockedValue = getLocked();
        String lockedValueAsString = "";
        lockedValueAsString = lockedValue.toString();
        sb.append("locked=").append(urlEncode(lockedValueAsString)).append("");
        return sb.toString();
    }

    public static String urlEncode(String s) {
        try {
            return URLEncoder.encode(s, StandardCharsets.UTF_8.name());
        } catch (UnsupportedEncodingException e) {
            throw new RuntimeException(StandardCharsets.UTF_8.name() + " is unsupported", e);
        }
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n		");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("asset");
        openapiFields.add("free");
        openapiFields.add("locked");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to
     *     DailyAccountSnapshotResponseSnapshotVosInnerDataBalancesInner
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!DailyAccountSnapshotResponseSnapshotVosInnerDataBalancesInner.openapiRequiredFields
                    .isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(
                        String.format(
                                "The required field(s) %s in"
                                    + " DailyAccountSnapshotResponseSnapshotVosInnerDataBalancesInner"
                                    + " is not found in the empty JSON string",
                                DailyAccountSnapshotResponseSnapshotVosInnerDataBalancesInner
                                        .openapiRequiredFields
                                        .toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if ((jsonObj.get("asset") != null && !jsonObj.get("asset").isJsonNull())
                && !jsonObj.get("asset").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `asset` to be a primitive type in the JSON string"
                                    + " but got `%s`",
                            jsonObj.get("asset").toString()));
        }
        if ((jsonObj.get("free") != null && !jsonObj.get("free").isJsonNull())
                && !jsonObj.get("free").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `free` to be a primitive type in the JSON string"
                                    + " but got `%s`",
                            jsonObj.get("free").toString()));
        }
        if ((jsonObj.get("locked") != null && !jsonObj.get("locked").isJsonNull())
                && !jsonObj.get("locked").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `locked` to be a primitive type in the JSON string"
                                    + " but got `%s`",
                            jsonObj.get("locked").toString()));
        }
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!DailyAccountSnapshotResponseSnapshotVosInnerDataBalancesInner.class
                    .isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes
                // 'DailyAccountSnapshotResponseSnapshotVosInnerDataBalancesInner' and
                // its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<DailyAccountSnapshotResponseSnapshotVosInnerDataBalancesInner>
                    thisAdapter =
                            gson.getDelegateAdapter(
                                    this,
                                    TypeToken.get(
                                            DailyAccountSnapshotResponseSnapshotVosInnerDataBalancesInner
                                                    .class));

            return (TypeAdapter<T>)
                    new TypeAdapter<
                            DailyAccountSnapshotResponseSnapshotVosInnerDataBalancesInner>() {
                        @Override
                        public void write(
                                JsonWriter out,
                                DailyAccountSnapshotResponseSnapshotVosInnerDataBalancesInner value)
                                throws IOException {
                            JsonElement obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                            elementAdapter.write(out, obj);
                        }

                        @Override
                        public DailyAccountSnapshotResponseSnapshotVosInnerDataBalancesInner read(
                                JsonReader in) throws IOException {
                            JsonElement jsonElement = elementAdapter.read(in);
                            // validateJsonElement(jsonElement);
                            return thisAdapter.fromJsonTree(jsonElement);
                        }
                    }.nullSafe();
        }
    }

    /**
     * Create an instance of DailyAccountSnapshotResponseSnapshotVosInnerDataBalancesInner given an
     * JSON string
     *
     * @param jsonString JSON string
     * @return An instance of DailyAccountSnapshotResponseSnapshotVosInnerDataBalancesInner
     * @throws IOException if the JSON string is invalid with respect to
     *     DailyAccountSnapshotResponseSnapshotVosInnerDataBalancesInner
     */
    public static DailyAccountSnapshotResponseSnapshotVosInnerDataBalancesInner fromJson(
            String jsonString) throws IOException {
        return JSON.getGson()
                .fromJson(
                        jsonString,
                        DailyAccountSnapshotResponseSnapshotVosInnerDataBalancesInner.class);
    }

    /**
     * Convert an instance of DailyAccountSnapshotResponseSnapshotVosInnerDataBalancesInner to an
     * JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
