/*
 * Sub Account REST API
 * Create and manage sub-accounts, control permissions, and transfer assets via the Sub Account API.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.client.sub_account.rest.model;

import com.google.gson.JsonElement;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import jakarta.validation.constraints.*;
import java.io.IOException;
import org.hibernate.validator.constraints.*;

/** Gets or Sets transferFunctionAccountType */
@JsonAdapter(TransferFunctionAccountType.Adapter.class)
public enum TransferFunctionAccountType {
    SPOT("SPOT"),

    MARGIN("MARGIN"),

    ISOLATED_MARGIN("ISOLATED_MARGIN"),

    USDT_FUTURE("USDT_FUTURE"),

    COIN_FUTURE("COIN_FUTURE");

    private String value;

    TransferFunctionAccountType(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }

    public static TransferFunctionAccountType fromValue(String value) {
        for (TransferFunctionAccountType b : TransferFunctionAccountType.values()) {
            if (b.value.equals(value)) {
                return b;
            }
        }
        throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<TransferFunctionAccountType> {
        @Override
        public void write(
                final JsonWriter jsonWriter, final TransferFunctionAccountType enumeration)
                throws IOException {
            jsonWriter.value(enumeration.getValue());
        }

        @Override
        public TransferFunctionAccountType read(final JsonReader jsonReader) throws IOException {
            String value = jsonReader.nextString();
            return TransferFunctionAccountType.fromValue(value);
        }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        String value = jsonElement.getAsString();
        TransferFunctionAccountType.fromValue(value);
    }
}
