/*
 * Stocks Trading REST API
 * REST APIs for Binance Stocks Trading. All endpoints under `/sapi/v1/equity/_*`.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.client.stocks.rest.model;

import com.binance.connector.client.stocks.rest.JSON;
import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import jakarta.validation.constraints.*;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Objects;
import org.hibernate.validator.constraints.*;
import org.openapitools.jackson.nullable.JsonNullable;

/** ExchangeInfoResponseSymbolsInner */
@jakarta.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.22.0")
public class ExchangeInfoResponseSymbolsInner {
    public static final String SERIALIZED_NAME_SYMBOL = "symbol";

    @SerializedName(SERIALIZED_NAME_SYMBOL)
    @jakarta.annotation.Nullable
    private String symbol;

    public static final String SERIALIZED_NAME_TRADABILITY = "tradability";

    @SerializedName(SERIALIZED_NAME_TRADABILITY)
    @jakarta.annotation.Nullable
    private String tradability;

    public static final String SERIALIZED_NAME_TRADABILITY_UPDATE_TIME = "tradabilityUpdateTime";

    @SerializedName(SERIALIZED_NAME_TRADABILITY_UPDATE_TIME)
    @jakarta.annotation.Nullable
    private Long tradabilityUpdateTime;

    public static final String SERIALIZED_NAME_OVERNIGHT_SUPPORTED = "overnightSupported";

    @SerializedName(SERIALIZED_NAME_OVERNIGHT_SUPPORTED)
    @jakarta.annotation.Nullable
    private Boolean overnightSupported;

    public static final String SERIALIZED_NAME_FRACTIONABLE = "fractionable";

    @SerializedName(SERIALIZED_NAME_FRACTIONABLE)
    @jakarta.annotation.Nullable
    private Boolean fractionable;

    public static final String SERIALIZED_NAME_FRACTIONABLE_EH = "fractionableEh";

    @SerializedName(SERIALIZED_NAME_FRACTIONABLE_EH)
    @jakarta.annotation.Nullable
    private Boolean fractionableEh;

    public static final String SERIALIZED_NAME_EXTENDED_SESSION = "extendedSession";

    @SerializedName(SERIALIZED_NAME_EXTENDED_SESSION)
    @jakarta.annotation.Nullable
    private Boolean extendedSession;

    public static final String SERIALIZED_NAME_MAX_NUM_ORDERS = "maxNumOrders";

    @SerializedName(SERIALIZED_NAME_MAX_NUM_ORDERS)
    @jakarta.annotation.Nullable
    private Integer maxNumOrders;

    public static final String SERIALIZED_NAME_STEP_SIZE = "stepSize";

    @SerializedName(SERIALIZED_NAME_STEP_SIZE)
    @jakarta.annotation.Nullable
    private String stepSize;

    public static final String SERIALIZED_NAME_MULTIPLIER_UP = "multiplierUp";

    @SerializedName(SERIALIZED_NAME_MULTIPLIER_UP)
    @jakarta.annotation.Nullable
    private String multiplierUp;

    public static final String SERIALIZED_NAME_MULTIPLIER_DOWN = "multiplierDown";

    @SerializedName(SERIALIZED_NAME_MULTIPLIER_DOWN)
    @jakarta.annotation.Nullable
    private String multiplierDown;

    public static final String SERIALIZED_NAME_MIN_QTY = "minQty";

    @SerializedName(SERIALIZED_NAME_MIN_QTY)
    @jakarta.annotation.Nullable
    private String minQty;

    public static final String SERIALIZED_NAME_MAX_QTY = "maxQty";

    @SerializedName(SERIALIZED_NAME_MAX_QTY)
    @jakarta.annotation.Nullable
    private String maxQty;

    public static final String SERIALIZED_NAME_MIN_NOTIONAL = "minNotional";

    @SerializedName(SERIALIZED_NAME_MIN_NOTIONAL)
    @jakarta.annotation.Nullable
    private String minNotional;

    public static final String SERIALIZED_NAME_MAX_NOTIONAL = "maxNotional";

    @SerializedName(SERIALIZED_NAME_MAX_NOTIONAL)
    @jakarta.annotation.Nullable
    private String maxNotional;

    public static final String SERIALIZED_NAME_LISTING_TIME = "listingTime";

    @SerializedName(SERIALIZED_NAME_LISTING_TIME)
    @jakarta.annotation.Nullable
    private Long listingTime;

    public static final String SERIALIZED_NAME_DELISTING_TIME = "delistingTime";

    @SerializedName(SERIALIZED_NAME_DELISTING_TIME)
    @jakarta.annotation.Nullable
    private Long delistingTime;

    public ExchangeInfoResponseSymbolsInner() {}

    public ExchangeInfoResponseSymbolsInner symbol(@jakarta.annotation.Nullable String symbol) {
        this.symbol = symbol;
        return this;
    }

    /**
     * US-equity ticker, e.g. &#x60;AAPL&#x60;.
     *
     * @return symbol
     */
    @jakarta.annotation.Nullable
    public String getSymbol() {
        return symbol;
    }

    public void setSymbol(@jakarta.annotation.Nullable String symbol) {
        this.symbol = symbol;
    }

    public ExchangeInfoResponseSymbolsInner tradability(
            @jakarta.annotation.Nullable String tradability) {
        this.tradability = tradability;
        return this;
    }

    /**
     * Trading direction allowed — one of &#x60;BUY_SELL&#x60; / &#x60;BUY&#x60; / &#x60;SELL&#x60;
     * / &#x60;NONE&#x60;.
     *
     * @return tradability
     */
    @jakarta.annotation.Nullable
    public String getTradability() {
        return tradability;
    }

    public void setTradability(@jakarta.annotation.Nullable String tradability) {
        this.tradability = tradability;
    }

    public ExchangeInfoResponseSymbolsInner tradabilityUpdateTime(
            @jakarta.annotation.Nullable Long tradabilityUpdateTime) {
        this.tradabilityUpdateTime = tradabilityUpdateTime;
        return this;
    }

    /**
     * Last time the &#x60;tradability&#x60; value was updated (ms epoch).
     *
     * @return tradabilityUpdateTime
     */
    @jakarta.annotation.Nullable
    public Long getTradabilityUpdateTime() {
        return tradabilityUpdateTime;
    }

    public void setTradabilityUpdateTime(@jakarta.annotation.Nullable Long tradabilityUpdateTime) {
        this.tradabilityUpdateTime = tradabilityUpdateTime;
    }

    public ExchangeInfoResponseSymbolsInner overnightSupported(
            @jakarta.annotation.Nullable Boolean overnightSupported) {
        this.overnightSupported = overnightSupported;
        return this;
    }

    /**
     * Whether the symbol supports overnight trading.
     *
     * @return overnightSupported
     */
    @jakarta.annotation.Nullable
    public Boolean getOvernightSupported() {
        return overnightSupported;
    }

    public void setOvernightSupported(@jakarta.annotation.Nullable Boolean overnightSupported) {
        this.overnightSupported = overnightSupported;
    }

    public ExchangeInfoResponseSymbolsInner fractionable(
            @jakarta.annotation.Nullable Boolean fractionable) {
        this.fractionable = fractionable;
        return this;
    }

    /**
     * Whether fractional shares are supported during the regular session.
     *
     * @return fractionable
     */
    @jakarta.annotation.Nullable
    public Boolean getFractionable() {
        return fractionable;
    }

    public void setFractionable(@jakarta.annotation.Nullable Boolean fractionable) {
        this.fractionable = fractionable;
    }

    public ExchangeInfoResponseSymbolsInner fractionableEh(
            @jakarta.annotation.Nullable Boolean fractionableEh) {
        this.fractionableEh = fractionableEh;
        return this;
    }

    /**
     * Whether fractional shares are supported during extended hours.
     *
     * @return fractionableEh
     */
    @jakarta.annotation.Nullable
    public Boolean getFractionableEh() {
        return fractionableEh;
    }

    public void setFractionableEh(@jakarta.annotation.Nullable Boolean fractionableEh) {
        this.fractionableEh = fractionableEh;
    }

    public ExchangeInfoResponseSymbolsInner extendedSession(
            @jakarta.annotation.Nullable Boolean extendedSession) {
        this.extendedSession = extendedSession;
        return this;
    }

    /**
     * Whether extended-session trading is enabled.
     *
     * @return extendedSession
     */
    @jakarta.annotation.Nullable
    public Boolean getExtendedSession() {
        return extendedSession;
    }

    public void setExtendedSession(@jakarta.annotation.Nullable Boolean extendedSession) {
        this.extendedSession = extendedSession;
    }

    public ExchangeInfoResponseSymbolsInner maxNumOrders(
            @jakarta.annotation.Nullable Integer maxNumOrders) {
        this.maxNumOrders = maxNumOrders;
        return this;
    }

    /**
     * Maximum number of open orders a user may have for this symbol.
     *
     * @return maxNumOrders
     */
    @jakarta.annotation.Nullable
    public Integer getMaxNumOrders() {
        return maxNumOrders;
    }

    public void setMaxNumOrders(@jakarta.annotation.Nullable Integer maxNumOrders) {
        this.maxNumOrders = maxNumOrders;
    }

    public ExchangeInfoResponseSymbolsInner stepSize(@jakarta.annotation.Nullable String stepSize) {
        this.stepSize = stepSize;
        return this;
    }

    /**
     * Lot size — minimum increment for &#x60;quantity&#x60;.
     *
     * @return stepSize
     */
    @jakarta.annotation.Nullable
    public String getStepSize() {
        return stepSize;
    }

    public void setStepSize(@jakarta.annotation.Nullable String stepSize) {
        this.stepSize = stepSize;
    }

    public ExchangeInfoResponseSymbolsInner multiplierUp(
            @jakarta.annotation.Nullable String multiplierUp) {
        this.multiplierUp = multiplierUp;
        return this;
    }

    /**
     * Upper price multiplier limit relative to reference.
     *
     * @return multiplierUp
     */
    @jakarta.annotation.Nullable
    public String getMultiplierUp() {
        return multiplierUp;
    }

    public void setMultiplierUp(@jakarta.annotation.Nullable String multiplierUp) {
        this.multiplierUp = multiplierUp;
    }

    public ExchangeInfoResponseSymbolsInner multiplierDown(
            @jakarta.annotation.Nullable String multiplierDown) {
        this.multiplierDown = multiplierDown;
        return this;
    }

    /**
     * Lower price multiplier limit relative to reference.
     *
     * @return multiplierDown
     */
    @jakarta.annotation.Nullable
    public String getMultiplierDown() {
        return multiplierDown;
    }

    public void setMultiplierDown(@jakarta.annotation.Nullable String multiplierDown) {
        this.multiplierDown = multiplierDown;
    }

    public ExchangeInfoResponseSymbolsInner minQty(@jakarta.annotation.Nullable String minQty) {
        this.minQty = minQty;
        return this;
    }

    /**
     * Minimum allowed &#x60;quantity&#x60;.
     *
     * @return minQty
     */
    @jakarta.annotation.Nullable
    public String getMinQty() {
        return minQty;
    }

    public void setMinQty(@jakarta.annotation.Nullable String minQty) {
        this.minQty = minQty;
    }

    public ExchangeInfoResponseSymbolsInner maxQty(@jakarta.annotation.Nullable String maxQty) {
        this.maxQty = maxQty;
        return this;
    }

    /**
     * Maximum allowed &#x60;quantity&#x60;.
     *
     * @return maxQty
     */
    @jakarta.annotation.Nullable
    public String getMaxQty() {
        return maxQty;
    }

    public void setMaxQty(@jakarta.annotation.Nullable String maxQty) {
        this.maxQty = maxQty;
    }

    public ExchangeInfoResponseSymbolsInner minNotional(
            @jakarta.annotation.Nullable String minNotional) {
        this.minNotional = minNotional;
        return this;
    }

    /**
     * Minimum order notional (USD).
     *
     * @return minNotional
     */
    @jakarta.annotation.Nullable
    public String getMinNotional() {
        return minNotional;
    }

    public void setMinNotional(@jakarta.annotation.Nullable String minNotional) {
        this.minNotional = minNotional;
    }

    public ExchangeInfoResponseSymbolsInner maxNotional(
            @jakarta.annotation.Nullable String maxNotional) {
        this.maxNotional = maxNotional;
        return this;
    }

    /**
     * Maximum order notional (USD).
     *
     * @return maxNotional
     */
    @jakarta.annotation.Nullable
    public String getMaxNotional() {
        return maxNotional;
    }

    public void setMaxNotional(@jakarta.annotation.Nullable String maxNotional) {
        this.maxNotional = maxNotional;
    }

    public ExchangeInfoResponseSymbolsInner listingTime(
            @jakarta.annotation.Nullable Long listingTime) {
        this.listingTime = listingTime;
        return this;
    }

    /**
     * Listing timestamp (ms epoch).
     *
     * @return listingTime
     */
    @jakarta.annotation.Nullable
    public Long getListingTime() {
        return listingTime;
    }

    public void setListingTime(@jakarta.annotation.Nullable Long listingTime) {
        this.listingTime = listingTime;
    }

    public ExchangeInfoResponseSymbolsInner delistingTime(
            @jakarta.annotation.Nullable Long delistingTime) {
        this.delistingTime = delistingTime;
        return this;
    }

    /**
     * Scheduled delisting timestamp (ms epoch); &#x60;null&#x60; if not scheduled for delisting.
     *
     * @return delistingTime
     */
    @jakarta.annotation.Nullable
    public Long getDelistingTime() {
        return delistingTime;
    }

    public void setDelistingTime(@jakarta.annotation.Nullable Long delistingTime) {
        this.delistingTime = delistingTime;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ExchangeInfoResponseSymbolsInner exchangeInfoResponseSymbolsInner =
                (ExchangeInfoResponseSymbolsInner) o;
        return Objects.equals(this.symbol, exchangeInfoResponseSymbolsInner.symbol)
                && Objects.equals(this.tradability, exchangeInfoResponseSymbolsInner.tradability)
                && Objects.equals(
                        this.tradabilityUpdateTime,
                        exchangeInfoResponseSymbolsInner.tradabilityUpdateTime)
                && Objects.equals(
                        this.overnightSupported,
                        exchangeInfoResponseSymbolsInner.overnightSupported)
                && Objects.equals(this.fractionable, exchangeInfoResponseSymbolsInner.fractionable)
                && Objects.equals(
                        this.fractionableEh, exchangeInfoResponseSymbolsInner.fractionableEh)
                && Objects.equals(
                        this.extendedSession, exchangeInfoResponseSymbolsInner.extendedSession)
                && Objects.equals(this.maxNumOrders, exchangeInfoResponseSymbolsInner.maxNumOrders)
                && Objects.equals(this.stepSize, exchangeInfoResponseSymbolsInner.stepSize)
                && Objects.equals(this.multiplierUp, exchangeInfoResponseSymbolsInner.multiplierUp)
                && Objects.equals(
                        this.multiplierDown, exchangeInfoResponseSymbolsInner.multiplierDown)
                && Objects.equals(this.minQty, exchangeInfoResponseSymbolsInner.minQty)
                && Objects.equals(this.maxQty, exchangeInfoResponseSymbolsInner.maxQty)
                && Objects.equals(this.minNotional, exchangeInfoResponseSymbolsInner.minNotional)
                && Objects.equals(this.maxNotional, exchangeInfoResponseSymbolsInner.maxNotional)
                && Objects.equals(this.listingTime, exchangeInfoResponseSymbolsInner.listingTime)
                && Objects.equals(
                        this.delistingTime, exchangeInfoResponseSymbolsInner.delistingTime);
    }

    private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
        return a == b
                || (a != null
                        && b != null
                        && a.isPresent()
                        && b.isPresent()
                        && Objects.deepEquals(a.get(), b.get()));
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                symbol,
                tradability,
                tradabilityUpdateTime,
                overnightSupported,
                fractionable,
                fractionableEh,
                extendedSession,
                maxNumOrders,
                stepSize,
                multiplierUp,
                multiplierDown,
                minQty,
                maxQty,
                minNotional,
                maxNotional,
                listingTime,
                delistingTime);
    }

    private static <T> int hashCodeNullable(JsonNullable<T> a) {
        if (a == null) {
            return 1;
        }
        return a.isPresent() ? Arrays.deepHashCode(new Object[] {a.get()}) : 31;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ExchangeInfoResponseSymbolsInner {\n");
        sb.append("		symbol: ").append(toIndentedString(symbol)).append("\n");
        sb.append("		tradability: ").append(toIndentedString(tradability)).append("\n");
        sb.append("		tradabilityUpdateTime: ")
                .append(toIndentedString(tradabilityUpdateTime))
                .append("\n");
        sb.append("		overnightSupported: ")
                .append(toIndentedString(overnightSupported))
                .append("\n");
        sb.append("		fractionable: ").append(toIndentedString(fractionable)).append("\n");
        sb.append("		fractionableEh: ").append(toIndentedString(fractionableEh)).append("\n");
        sb.append("		extendedSession: ").append(toIndentedString(extendedSession)).append("\n");
        sb.append("		maxNumOrders: ").append(toIndentedString(maxNumOrders)).append("\n");
        sb.append("		stepSize: ").append(toIndentedString(stepSize)).append("\n");
        sb.append("		multiplierUp: ").append(toIndentedString(multiplierUp)).append("\n");
        sb.append("		multiplierDown: ").append(toIndentedString(multiplierDown)).append("\n");
        sb.append("		minQty: ").append(toIndentedString(minQty)).append("\n");
        sb.append("		maxQty: ").append(toIndentedString(maxQty)).append("\n");
        sb.append("		minNotional: ").append(toIndentedString(minNotional)).append("\n");
        sb.append("		maxNotional: ").append(toIndentedString(maxNotional)).append("\n");
        sb.append("		listingTime: ").append(toIndentedString(listingTime)).append("\n");
        sb.append("		delistingTime: ").append(toIndentedString(delistingTime)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    public String toUrlQueryString() {
        StringBuilder sb = new StringBuilder();

        Object symbolValue = getSymbol();
        String symbolValueAsString = "";
        symbolValueAsString = symbolValue.toString();
        sb.append("symbol=").append(urlEncode(symbolValueAsString)).append("");
        Object tradabilityValue = getTradability();
        String tradabilityValueAsString = "";
        tradabilityValueAsString = tradabilityValue.toString();
        sb.append("tradability=").append(urlEncode(tradabilityValueAsString)).append("");
        Object tradabilityUpdateTimeValue = getTradabilityUpdateTime();
        String tradabilityUpdateTimeValueAsString = "";
        tradabilityUpdateTimeValueAsString = tradabilityUpdateTimeValue.toString();
        sb.append("tradabilityUpdateTime=")
                .append(urlEncode(tradabilityUpdateTimeValueAsString))
                .append("");
        Object overnightSupportedValue = getOvernightSupported();
        String overnightSupportedValueAsString = "";
        overnightSupportedValueAsString = overnightSupportedValue.toString();
        sb.append("overnightSupported=")
                .append(urlEncode(overnightSupportedValueAsString))
                .append("");
        Object fractionableValue = getFractionable();
        String fractionableValueAsString = "";
        fractionableValueAsString = fractionableValue.toString();
        sb.append("fractionable=").append(urlEncode(fractionableValueAsString)).append("");
        Object fractionableEhValue = getFractionableEh();
        String fractionableEhValueAsString = "";
        fractionableEhValueAsString = fractionableEhValue.toString();
        sb.append("fractionableEh=").append(urlEncode(fractionableEhValueAsString)).append("");
        Object extendedSessionValue = getExtendedSession();
        String extendedSessionValueAsString = "";
        extendedSessionValueAsString = extendedSessionValue.toString();
        sb.append("extendedSession=").append(urlEncode(extendedSessionValueAsString)).append("");
        Object maxNumOrdersValue = getMaxNumOrders();
        String maxNumOrdersValueAsString = "";
        maxNumOrdersValueAsString = maxNumOrdersValue.toString();
        sb.append("maxNumOrders=").append(urlEncode(maxNumOrdersValueAsString)).append("");
        Object stepSizeValue = getStepSize();
        String stepSizeValueAsString = "";
        stepSizeValueAsString = stepSizeValue.toString();
        sb.append("stepSize=").append(urlEncode(stepSizeValueAsString)).append("");
        Object multiplierUpValue = getMultiplierUp();
        String multiplierUpValueAsString = "";
        multiplierUpValueAsString = multiplierUpValue.toString();
        sb.append("multiplierUp=").append(urlEncode(multiplierUpValueAsString)).append("");
        Object multiplierDownValue = getMultiplierDown();
        String multiplierDownValueAsString = "";
        multiplierDownValueAsString = multiplierDownValue.toString();
        sb.append("multiplierDown=").append(urlEncode(multiplierDownValueAsString)).append("");
        Object minQtyValue = getMinQty();
        String minQtyValueAsString = "";
        minQtyValueAsString = minQtyValue.toString();
        sb.append("minQty=").append(urlEncode(minQtyValueAsString)).append("");
        Object maxQtyValue = getMaxQty();
        String maxQtyValueAsString = "";
        maxQtyValueAsString = maxQtyValue.toString();
        sb.append("maxQty=").append(urlEncode(maxQtyValueAsString)).append("");
        Object minNotionalValue = getMinNotional();
        String minNotionalValueAsString = "";
        minNotionalValueAsString = minNotionalValue.toString();
        sb.append("minNotional=").append(urlEncode(minNotionalValueAsString)).append("");
        Object maxNotionalValue = getMaxNotional();
        String maxNotionalValueAsString = "";
        maxNotionalValueAsString = maxNotionalValue.toString();
        sb.append("maxNotional=").append(urlEncode(maxNotionalValueAsString)).append("");
        Object listingTimeValue = getListingTime();
        String listingTimeValueAsString = "";
        listingTimeValueAsString = listingTimeValue.toString();
        sb.append("listingTime=").append(urlEncode(listingTimeValueAsString)).append("");
        Object delistingTimeValue = getDelistingTime();
        String delistingTimeValueAsString = "";
        delistingTimeValueAsString = delistingTimeValue.toString();
        sb.append("delistingTime=").append(urlEncode(delistingTimeValueAsString)).append("");
        return sb.toString();
    }

    public static String urlEncode(String s) {
        try {
            return URLEncoder.encode(s, StandardCharsets.UTF_8.name());
        } catch (UnsupportedEncodingException e) {
            throw new RuntimeException(StandardCharsets.UTF_8.name() + " is unsupported", e);
        }
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n		");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("symbol");
        openapiFields.add("tradability");
        openapiFields.add("tradabilityUpdateTime");
        openapiFields.add("overnightSupported");
        openapiFields.add("fractionable");
        openapiFields.add("fractionableEh");
        openapiFields.add("extendedSession");
        openapiFields.add("maxNumOrders");
        openapiFields.add("stepSize");
        openapiFields.add("multiplierUp");
        openapiFields.add("multiplierDown");
        openapiFields.add("minQty");
        openapiFields.add("maxQty");
        openapiFields.add("minNotional");
        openapiFields.add("maxNotional");
        openapiFields.add("listingTime");
        openapiFields.add("delistingTime");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to
     *     ExchangeInfoResponseSymbolsInner
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!ExchangeInfoResponseSymbolsInner.openapiRequiredFields
                    .isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(
                        String.format(
                                "The required field(s) %s in ExchangeInfoResponseSymbolsInner is"
                                        + " not found in the empty JSON string",
                                ExchangeInfoResponseSymbolsInner.openapiRequiredFields.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if ((jsonObj.get("symbol") != null && !jsonObj.get("symbol").isJsonNull())
                && !jsonObj.get("symbol").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `symbol` to be a primitive type in the JSON string"
                                    + " but got `%s`",
                            jsonObj.get("symbol").toString()));
        }
        if ((jsonObj.get("tradability") != null && !jsonObj.get("tradability").isJsonNull())
                && !jsonObj.get("tradability").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `tradability` to be a primitive type in the JSON"
                                    + " string but got `%s`",
                            jsonObj.get("tradability").toString()));
        }
        if ((jsonObj.get("stepSize") != null && !jsonObj.get("stepSize").isJsonNull())
                && !jsonObj.get("stepSize").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `stepSize` to be a primitive type in the JSON"
                                    + " string but got `%s`",
                            jsonObj.get("stepSize").toString()));
        }
        if ((jsonObj.get("multiplierUp") != null && !jsonObj.get("multiplierUp").isJsonNull())
                && !jsonObj.get("multiplierUp").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `multiplierUp` to be a primitive type in the JSON"
                                    + " string but got `%s`",
                            jsonObj.get("multiplierUp").toString()));
        }
        if ((jsonObj.get("multiplierDown") != null && !jsonObj.get("multiplierDown").isJsonNull())
                && !jsonObj.get("multiplierDown").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `multiplierDown` to be a primitive type in the JSON"
                                    + " string but got `%s`",
                            jsonObj.get("multiplierDown").toString()));
        }
        if ((jsonObj.get("minQty") != null && !jsonObj.get("minQty").isJsonNull())
                && !jsonObj.get("minQty").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `minQty` to be a primitive type in the JSON string"
                                    + " but got `%s`",
                            jsonObj.get("minQty").toString()));
        }
        if ((jsonObj.get("maxQty") != null && !jsonObj.get("maxQty").isJsonNull())
                && !jsonObj.get("maxQty").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `maxQty` to be a primitive type in the JSON string"
                                    + " but got `%s`",
                            jsonObj.get("maxQty").toString()));
        }
        if ((jsonObj.get("minNotional") != null && !jsonObj.get("minNotional").isJsonNull())
                && !jsonObj.get("minNotional").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `minNotional` to be a primitive type in the JSON"
                                    + " string but got `%s`",
                            jsonObj.get("minNotional").toString()));
        }
        if ((jsonObj.get("maxNotional") != null && !jsonObj.get("maxNotional").isJsonNull())
                && !jsonObj.get("maxNotional").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `maxNotional` to be a primitive type in the JSON"
                                    + " string but got `%s`",
                            jsonObj.get("maxNotional").toString()));
        }
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!ExchangeInfoResponseSymbolsInner.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'ExchangeInfoResponseSymbolsInner' and
                // its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<ExchangeInfoResponseSymbolsInner> thisAdapter =
                    gson.getDelegateAdapter(
                            this, TypeToken.get(ExchangeInfoResponseSymbolsInner.class));

            return (TypeAdapter<T>)
                    new TypeAdapter<ExchangeInfoResponseSymbolsInner>() {
                        @Override
                        public void write(JsonWriter out, ExchangeInfoResponseSymbolsInner value)
                                throws IOException {
                            JsonElement obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                            elementAdapter.write(out, obj);
                        }

                        @Override
                        public ExchangeInfoResponseSymbolsInner read(JsonReader in)
                                throws IOException {
                            JsonElement jsonElement = elementAdapter.read(in);
                            // validateJsonElement(jsonElement);
                            return thisAdapter.fromJsonTree(jsonElement);
                        }
                    }.nullSafe();
        }
    }

    /**
     * Create an instance of ExchangeInfoResponseSymbolsInner given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of ExchangeInfoResponseSymbolsInner
     * @throws IOException if the JSON string is invalid with respect to
     *     ExchangeInfoResponseSymbolsInner
     */
    public static ExchangeInfoResponseSymbolsInner fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, ExchangeInfoResponseSymbolsInner.class);
    }

    /**
     * Convert an instance of ExchangeInfoResponseSymbolsInner to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
