/*
 * Binance Spot WebSocket API
 * OpenAPI Specifications for the Binance Spot WebSocket API  API documents:   - [Github web-socket-api documentation file](https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-api.md)   - [General API information for web-socket-api on website](https://developers.binance.com/docs/binance-spot-api-docs/web-socket-api/general-api-information)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.client.spot.websocket.api.model;

import com.binance.connector.client.common.websocket.dtos.BaseDTO;
import com.binance.connector.client.spot.websocket.api.JSON;
import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.TreeMap;
import java.util.stream.Collectors;
import org.hibernate.validator.constraints.*;

/** ExchangeInfoResponseResult */
@jakarta.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.12.0")
public class ExchangeInfoResponseResult extends BaseDTO {
    public static final String SERIALIZED_NAME_TIMEZONE = "timezone";

    @SerializedName(SERIALIZED_NAME_TIMEZONE)
    @jakarta.annotation.Nullable
    private String timezone;

    public static final String SERIALIZED_NAME_SERVER_TIME = "serverTime";

    @SerializedName(SERIALIZED_NAME_SERVER_TIME)
    @jakarta.annotation.Nullable
    private Long serverTime;

    public static final String SERIALIZED_NAME_RATE_LIMITS = "rateLimits";

    @SerializedName(SERIALIZED_NAME_RATE_LIMITS)
    @jakarta.annotation.Nullable
    private List<@Valid RateLimits> rateLimits;

    public static final String SERIALIZED_NAME_EXCHANGE_FILTERS = "exchangeFilters";

    @SerializedName(SERIALIZED_NAME_EXCHANGE_FILTERS)
    @jakarta.annotation.Nullable
    private List<ExchangeFilters> exchangeFilters;

    public static final String SERIALIZED_NAME_SYMBOLS = "symbols";

    @SerializedName(SERIALIZED_NAME_SYMBOLS)
    @jakarta.annotation.Nullable
    private List<@Valid ExchangeInfoResponseResultSymbolsInner> symbols;

    public static final String SERIALIZED_NAME_SORS = "sors";

    @SerializedName(SERIALIZED_NAME_SORS)
    @jakarta.annotation.Nullable
    private List<@Valid ExchangeInfoResponseResultSorsInner> sors;

    public ExchangeInfoResponseResult() {}

    public ExchangeInfoResponseResult timezone(@jakarta.annotation.Nullable String timezone) {
        this.timezone = timezone;
        return this;
    }

    /**
     * Get timezone
     *
     * @return timezone
     */
    @jakarta.annotation.Nullable
    public String getTimezone() {
        return timezone;
    }

    public void setTimezone(@jakarta.annotation.Nullable String timezone) {
        this.timezone = timezone;
    }

    public ExchangeInfoResponseResult serverTime(@jakarta.annotation.Nullable Long serverTime) {
        this.serverTime = serverTime;
        return this;
    }

    /**
     * Get serverTime
     *
     * @return serverTime
     */
    @jakarta.annotation.Nullable
    public Long getServerTime() {
        return serverTime;
    }

    public void setServerTime(@jakarta.annotation.Nullable Long serverTime) {
        this.serverTime = serverTime;
    }

    public ExchangeInfoResponseResult rateLimits(
            @jakarta.annotation.Nullable List<@Valid RateLimits> rateLimits) {
        this.rateLimits = rateLimits;
        return this;
    }

    public ExchangeInfoResponseResult addRateLimitsItem(RateLimits rateLimitsItem) {
        if (this.rateLimits == null) {
            this.rateLimits = new ArrayList<>();
        }
        this.rateLimits.add(rateLimitsItem);
        return this;
    }

    /**
     * Get rateLimits
     *
     * @return rateLimits
     */
    @jakarta.annotation.Nullable
    @Valid
    public List<@Valid RateLimits> getRateLimits() {
        return rateLimits;
    }

    public void setRateLimits(@jakarta.annotation.Nullable List<@Valid RateLimits> rateLimits) {
        this.rateLimits = rateLimits;
    }

    public ExchangeInfoResponseResult exchangeFilters(
            @jakarta.annotation.Nullable List<ExchangeFilters> exchangeFilters) {
        this.exchangeFilters = exchangeFilters;
        return this;
    }

    public ExchangeInfoResponseResult addExchangeFiltersItem(ExchangeFilters exchangeFiltersItem) {
        if (this.exchangeFilters == null) {
            this.exchangeFilters = new ArrayList<>();
        }
        this.exchangeFilters.add(exchangeFiltersItem);
        return this;
    }

    /**
     * Get exchangeFilters
     *
     * @return exchangeFilters
     */
    @jakarta.annotation.Nullable
    @Valid
    public List<ExchangeFilters> getExchangeFilters() {
        return exchangeFilters;
    }

    public void setExchangeFilters(
            @jakarta.annotation.Nullable List<ExchangeFilters> exchangeFilters) {
        this.exchangeFilters = exchangeFilters;
    }

    public ExchangeInfoResponseResult symbols(
            @jakarta.annotation.Nullable
                    List<@Valid ExchangeInfoResponseResultSymbolsInner> symbols) {
        this.symbols = symbols;
        return this;
    }

    public ExchangeInfoResponseResult addSymbolsItem(
            ExchangeInfoResponseResultSymbolsInner symbolsItem) {
        if (this.symbols == null) {
            this.symbols = new ArrayList<>();
        }
        this.symbols.add(symbolsItem);
        return this;
    }

    /**
     * Get symbols
     *
     * @return symbols
     */
    @jakarta.annotation.Nullable
    @Valid
    public List<@Valid ExchangeInfoResponseResultSymbolsInner> getSymbols() {
        return symbols;
    }

    public void setSymbols(
            @jakarta.annotation.Nullable
                    List<@Valid ExchangeInfoResponseResultSymbolsInner> symbols) {
        this.symbols = symbols;
    }

    public ExchangeInfoResponseResult sors(
            @jakarta.annotation.Nullable List<@Valid ExchangeInfoResponseResultSorsInner> sors) {
        this.sors = sors;
        return this;
    }

    public ExchangeInfoResponseResult addSorsItem(ExchangeInfoResponseResultSorsInner sorsItem) {
        if (this.sors == null) {
            this.sors = new ArrayList<>();
        }
        this.sors.add(sorsItem);
        return this;
    }

    /**
     * Get sors
     *
     * @return sors
     */
    @jakarta.annotation.Nullable
    @Valid
    public List<@Valid ExchangeInfoResponseResultSorsInner> getSors() {
        return sors;
    }

    public void setSors(
            @jakarta.annotation.Nullable List<@Valid ExchangeInfoResponseResultSorsInner> sors) {
        this.sors = sors;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ExchangeInfoResponseResult exchangeInfoResponseResult = (ExchangeInfoResponseResult) o;
        return Objects.equals(this.timezone, exchangeInfoResponseResult.timezone)
                && Objects.equals(this.serverTime, exchangeInfoResponseResult.serverTime)
                && Objects.equals(this.rateLimits, exchangeInfoResponseResult.rateLimits)
                && Objects.equals(this.exchangeFilters, exchangeInfoResponseResult.exchangeFilters)
                && Objects.equals(this.symbols, exchangeInfoResponseResult.symbols)
                && Objects.equals(this.sors, exchangeInfoResponseResult.sors);
    }

    @Override
    public int hashCode() {
        return Objects.hash(timezone, serverTime, rateLimits, exchangeFilters, symbols, sors);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ExchangeInfoResponseResult {\n");
        sb.append("		timezone: ").append(toIndentedString(timezone)).append("\n");
        sb.append("		serverTime: ").append(toIndentedString(serverTime)).append("\n");
        sb.append("		rateLimits: ").append(toIndentedString(rateLimits)).append("\n");
        sb.append("		exchangeFilters: ").append(toIndentedString(exchangeFilters)).append("\n");
        sb.append("		symbols: ").append(toIndentedString(symbols)).append("\n");
        sb.append("		sors: ").append(toIndentedString(sors)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    public String toUrlQueryString() {
        StringBuilder sb = new StringBuilder();
        Map<String, String> valMap = new TreeMap<String, String>();
        valMap.put("apiKey", getApiKey());
        String timezoneValue = getTimezone();
        if (timezoneValue != null) {
            String timezoneValueAsString = timezoneValue.toString();
            valMap.put("timezone", timezoneValueAsString);
        }
        Long serverTimeValue = getServerTime();
        if (serverTimeValue != null) {
            String serverTimeValueAsString = serverTimeValue.toString();
            valMap.put("serverTime", serverTimeValueAsString);
        }
        List<@Valid RateLimits> rateLimitsValue = getRateLimits();
        if (rateLimitsValue != null) {
            String rateLimitsValueAsString = JSON.getGson().toJson(rateLimitsValue);
            valMap.put("rateLimits", rateLimitsValueAsString);
        }
        List<ExchangeFilters> exchangeFiltersValue = getExchangeFilters();
        if (exchangeFiltersValue != null) {
            String exchangeFiltersValueAsString = JSON.getGson().toJson(exchangeFiltersValue);
            valMap.put("exchangeFilters", exchangeFiltersValueAsString);
        }
        List<@Valid ExchangeInfoResponseResultSymbolsInner> symbolsValue = getSymbols();
        if (symbolsValue != null) {
            String symbolsValueAsString = JSON.getGson().toJson(symbolsValue);
            valMap.put("symbols", symbolsValueAsString);
        }
        List<@Valid ExchangeInfoResponseResultSorsInner> sorsValue = getSors();
        if (sorsValue != null) {
            String sorsValueAsString = JSON.getGson().toJson(sorsValue);
            valMap.put("sors", sorsValueAsString);
        }

        valMap.put("timestamp", getTimestamp());
        return asciiEncode(
                valMap.keySet().stream()
                        .map(key -> key + "=" + valMap.get(key))
                        .collect(Collectors.joining("&")));
    }

    public Map<String, Object> toMap() {
        Map<String, Object> valMap = new TreeMap<String, Object>();
        valMap.put("apiKey", getApiKey());
        Object timezoneValue = getTimezone();
        if (timezoneValue != null) {
            valMap.put("timezone", timezoneValue);
        }
        Object serverTimeValue = getServerTime();
        if (serverTimeValue != null) {
            valMap.put("serverTime", serverTimeValue);
        }
        Object rateLimitsValue = getRateLimits();
        if (rateLimitsValue != null) {
            valMap.put("rateLimits", rateLimitsValue);
        }
        Object exchangeFiltersValue = getExchangeFilters();
        if (exchangeFiltersValue != null) {
            valMap.put("exchangeFilters", exchangeFiltersValue);
        }
        Object symbolsValue = getSymbols();
        if (symbolsValue != null) {
            valMap.put("symbols", symbolsValue);
        }
        Object sorsValue = getSors();
        if (sorsValue != null) {
            valMap.put("sors", sorsValue);
        }

        valMap.put("timestamp", getTimestamp());
        return valMap;
    }

    public static String asciiEncode(String s) {
        return new String(s.getBytes(), StandardCharsets.US_ASCII);
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n		");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("timezone");
        openapiFields.add("serverTime");
        openapiFields.add("rateLimits");
        openapiFields.add("exchangeFilters");
        openapiFields.add("symbols");
        openapiFields.add("sors");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to ExchangeInfoResponseResult
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!ExchangeInfoResponseResult.openapiRequiredFields
                    .isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(
                        String.format(
                                "The required field(s) %s in ExchangeInfoResponseResult is not"
                                        + " found in the empty JSON string",
                                ExchangeInfoResponseResult.openapiRequiredFields.toString()));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!ExchangeInfoResponseResult.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(
                        String.format(
                                "The field `%s` in the JSON string is not defined in the"
                                        + " `ExchangeInfoResponseResult` properties. JSON: %s",
                                entry.getKey(), jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if ((jsonObj.get("timezone") != null && !jsonObj.get("timezone").isJsonNull())
                && !jsonObj.get("timezone").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `timezone` to be a primitive type in the JSON"
                                    + " string but got `%s`",
                            jsonObj.get("timezone").toString()));
        }
        if (jsonObj.get("rateLimits") != null && !jsonObj.get("rateLimits").isJsonNull()) {
            JsonArray jsonArrayrateLimits = jsonObj.getAsJsonArray("rateLimits");
            if (jsonArrayrateLimits != null) {
                // ensure the json data is an array
                if (!jsonObj.get("rateLimits").isJsonArray()) {
                    throw new IllegalArgumentException(
                            String.format(
                                    "Expected the field `rateLimits` to be an array in the JSON"
                                            + " string but got `%s`",
                                    jsonObj.get("rateLimits").toString()));
                }

                // validate the optional field `rateLimits` (array)
                for (int i = 0; i < jsonArrayrateLimits.size(); i++) {
                    RateLimits.validateJsonElement(jsonArrayrateLimits.get(i));
                }
                ;
            }
        }
        if (jsonObj.get("exchangeFilters") != null
                && !jsonObj.get("exchangeFilters").isJsonNull()) {
            JsonArray jsonArrayexchangeFilters = jsonObj.getAsJsonArray("exchangeFilters");
            if (jsonArrayexchangeFilters != null) {
                // ensure the json data is an array
                if (!jsonObj.get("exchangeFilters").isJsonArray()) {
                    throw new IllegalArgumentException(
                            String.format(
                                    "Expected the field `exchangeFilters` to be an array in the"
                                            + " JSON string but got `%s`",
                                    jsonObj.get("exchangeFilters").toString()));
                }

                // validate the optional field `exchangeFilters` (array)
                for (int i = 0; i < jsonArrayexchangeFilters.size(); i++) {
                    ExchangeFilters.validateJsonElement(jsonArrayexchangeFilters.get(i));
                }
                ;
            }
        }
        if (jsonObj.get("symbols") != null && !jsonObj.get("symbols").isJsonNull()) {
            JsonArray jsonArraysymbols = jsonObj.getAsJsonArray("symbols");
            if (jsonArraysymbols != null) {
                // ensure the json data is an array
                if (!jsonObj.get("symbols").isJsonArray()) {
                    throw new IllegalArgumentException(
                            String.format(
                                    "Expected the field `symbols` to be an array in the JSON string"
                                            + " but got `%s`",
                                    jsonObj.get("symbols").toString()));
                }

                // validate the optional field `symbols` (array)
                for (int i = 0; i < jsonArraysymbols.size(); i++) {
                    ExchangeInfoResponseResultSymbolsInner.validateJsonElement(
                            jsonArraysymbols.get(i));
                }
                ;
            }
        }
        if (jsonObj.get("sors") != null && !jsonObj.get("sors").isJsonNull()) {
            JsonArray jsonArraysors = jsonObj.getAsJsonArray("sors");
            if (jsonArraysors != null) {
                // ensure the json data is an array
                if (!jsonObj.get("sors").isJsonArray()) {
                    throw new IllegalArgumentException(
                            String.format(
                                    "Expected the field `sors` to be an array in the JSON string"
                                            + " but got `%s`",
                                    jsonObj.get("sors").toString()));
                }

                // validate the optional field `sors` (array)
                for (int i = 0; i < jsonArraysors.size(); i++) {
                    ExchangeInfoResponseResultSorsInner.validateJsonElement(jsonArraysors.get(i));
                }
                ;
            }
        }
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!ExchangeInfoResponseResult.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'ExchangeInfoResponseResult' and its
                // subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<ExchangeInfoResponseResult> thisAdapter =
                    gson.getDelegateAdapter(this, TypeToken.get(ExchangeInfoResponseResult.class));

            return (TypeAdapter<T>)
                    new TypeAdapter<ExchangeInfoResponseResult>() {
                        @Override
                        public void write(JsonWriter out, ExchangeInfoResponseResult value)
                                throws IOException {
                            JsonElement obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                            elementAdapter.write(out, obj);
                        }

                        @Override
                        public ExchangeInfoResponseResult read(JsonReader in) throws IOException {
                            JsonElement jsonElement = elementAdapter.read(in);
                            // validateJsonElement(jsonElement);
                            return thisAdapter.fromJsonTree(jsonElement);
                        }
                    }.nullSafe();
        }
    }

    /**
     * Create an instance of ExchangeInfoResponseResult given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of ExchangeInfoResponseResult
     * @throws IOException if the JSON string is invalid with respect to ExchangeInfoResponseResult
     */
    public static ExchangeInfoResponseResult fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, ExchangeInfoResponseResult.class);
    }

    /**
     * Convert an instance of ExchangeInfoResponseResult to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
