/*
 * Binance Spot WebSocket API
 * OpenAPI Specifications for the Binance Spot WebSocket API  API documents:   - [Github web-socket-api documentation file](https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-api.md)   - [General API information for web-socket-api on website](https://developers.binance.com/docs/binance-spot-api-docs/web-socket-api/general-api-information)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.client.spot.websocket.api.model;

import com.binance.connector.client.common.websocket.dtos.BaseDTO;
import com.binance.connector.client.spot.websocket.api.JSON;
import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import jakarta.validation.constraints.*;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.TreeMap;
import java.util.stream.Collectors;
import org.hibernate.validator.constraints.*;

/** MyTradesResponseResultInner */
@jakarta.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.12.0")
public class MyTradesResponseResultInner extends BaseDTO {
    public static final String SERIALIZED_NAME_SYMBOL = "symbol";

    @SerializedName(SERIALIZED_NAME_SYMBOL)
    @jakarta.annotation.Nullable
    private String symbol;

    public static final String SERIALIZED_NAME_ID = "id";

    @SerializedName(SERIALIZED_NAME_ID)
    @jakarta.annotation.Nullable
    private Long id;

    public static final String SERIALIZED_NAME_ORDER_ID = "orderId";

    @SerializedName(SERIALIZED_NAME_ORDER_ID)
    @jakarta.annotation.Nullable
    private Long orderId;

    public static final String SERIALIZED_NAME_ORDER_LIST_ID = "orderListId";

    @SerializedName(SERIALIZED_NAME_ORDER_LIST_ID)
    @jakarta.annotation.Nullable
    private Long orderListId;

    public static final String SERIALIZED_NAME_PRICE = "price";

    @SerializedName(SERIALIZED_NAME_PRICE)
    @jakarta.annotation.Nullable
    private String price;

    public static final String SERIALIZED_NAME_QTY = "qty";

    @SerializedName(SERIALIZED_NAME_QTY)
    @jakarta.annotation.Nullable
    private String qty;

    public static final String SERIALIZED_NAME_QUOTE_QTY = "quoteQty";

    @SerializedName(SERIALIZED_NAME_QUOTE_QTY)
    @jakarta.annotation.Nullable
    private String quoteQty;

    public static final String SERIALIZED_NAME_COMMISSION = "commission";

    @SerializedName(SERIALIZED_NAME_COMMISSION)
    @jakarta.annotation.Nullable
    private String commission;

    public static final String SERIALIZED_NAME_COMMISSION_ASSET = "commissionAsset";

    @SerializedName(SERIALIZED_NAME_COMMISSION_ASSET)
    @jakarta.annotation.Nullable
    private String commissionAsset;

    public static final String SERIALIZED_NAME_TIME = "time";

    @SerializedName(SERIALIZED_NAME_TIME)
    @jakarta.annotation.Nullable
    private Long time;

    public static final String SERIALIZED_NAME_IS_BUYER = "isBuyer";

    @SerializedName(SERIALIZED_NAME_IS_BUYER)
    @jakarta.annotation.Nullable
    private Boolean isBuyer;

    public static final String SERIALIZED_NAME_IS_MAKER = "isMaker";

    @SerializedName(SERIALIZED_NAME_IS_MAKER)
    @jakarta.annotation.Nullable
    private Boolean isMaker;

    public static final String SERIALIZED_NAME_IS_BEST_MATCH = "isBestMatch";

    @SerializedName(SERIALIZED_NAME_IS_BEST_MATCH)
    @jakarta.annotation.Nullable
    private Boolean isBestMatch;

    public MyTradesResponseResultInner() {}

    public MyTradesResponseResultInner symbol(@jakarta.annotation.Nullable String symbol) {
        this.symbol = symbol;
        return this;
    }

    /**
     * Get symbol
     *
     * @return symbol
     */
    @jakarta.annotation.Nullable
    public String getSymbol() {
        return symbol;
    }

    public void setSymbol(@jakarta.annotation.Nullable String symbol) {
        this.symbol = symbol;
    }

    public MyTradesResponseResultInner id(@jakarta.annotation.Nullable Long id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     */
    @jakarta.annotation.Nullable
    public Long getId() {
        return id;
    }

    public void setId(@jakarta.annotation.Nullable Long id) {
        this.id = id;
    }

    public MyTradesResponseResultInner orderId(@jakarta.annotation.Nullable Long orderId) {
        this.orderId = orderId;
        return this;
    }

    /**
     * Get orderId
     *
     * @return orderId
     */
    @jakarta.annotation.Nullable
    public Long getOrderId() {
        return orderId;
    }

    public void setOrderId(@jakarta.annotation.Nullable Long orderId) {
        this.orderId = orderId;
    }

    public MyTradesResponseResultInner orderListId(@jakarta.annotation.Nullable Long orderListId) {
        this.orderListId = orderListId;
        return this;
    }

    /**
     * Get orderListId
     *
     * @return orderListId
     */
    @jakarta.annotation.Nullable
    public Long getOrderListId() {
        return orderListId;
    }

    public void setOrderListId(@jakarta.annotation.Nullable Long orderListId) {
        this.orderListId = orderListId;
    }

    public MyTradesResponseResultInner price(@jakarta.annotation.Nullable String price) {
        this.price = price;
        return this;
    }

    /**
     * Get price
     *
     * @return price
     */
    @jakarta.annotation.Nullable
    public String getPrice() {
        return price;
    }

    public void setPrice(@jakarta.annotation.Nullable String price) {
        this.price = price;
    }

    public MyTradesResponseResultInner qty(@jakarta.annotation.Nullable String qty) {
        this.qty = qty;
        return this;
    }

    /**
     * Get qty
     *
     * @return qty
     */
    @jakarta.annotation.Nullable
    public String getQty() {
        return qty;
    }

    public void setQty(@jakarta.annotation.Nullable String qty) {
        this.qty = qty;
    }

    public MyTradesResponseResultInner quoteQty(@jakarta.annotation.Nullable String quoteQty) {
        this.quoteQty = quoteQty;
        return this;
    }

    /**
     * Get quoteQty
     *
     * @return quoteQty
     */
    @jakarta.annotation.Nullable
    public String getQuoteQty() {
        return quoteQty;
    }

    public void setQuoteQty(@jakarta.annotation.Nullable String quoteQty) {
        this.quoteQty = quoteQty;
    }

    public MyTradesResponseResultInner commission(@jakarta.annotation.Nullable String commission) {
        this.commission = commission;
        return this;
    }

    /**
     * Get commission
     *
     * @return commission
     */
    @jakarta.annotation.Nullable
    public String getCommission() {
        return commission;
    }

    public void setCommission(@jakarta.annotation.Nullable String commission) {
        this.commission = commission;
    }

    public MyTradesResponseResultInner commissionAsset(
            @jakarta.annotation.Nullable String commissionAsset) {
        this.commissionAsset = commissionAsset;
        return this;
    }

    /**
     * Get commissionAsset
     *
     * @return commissionAsset
     */
    @jakarta.annotation.Nullable
    public String getCommissionAsset() {
        return commissionAsset;
    }

    public void setCommissionAsset(@jakarta.annotation.Nullable String commissionAsset) {
        this.commissionAsset = commissionAsset;
    }

    public MyTradesResponseResultInner time(@jakarta.annotation.Nullable Long time) {
        this.time = time;
        return this;
    }

    /**
     * Get time
     *
     * @return time
     */
    @jakarta.annotation.Nullable
    public Long getTime() {
        return time;
    }

    public void setTime(@jakarta.annotation.Nullable Long time) {
        this.time = time;
    }

    public MyTradesResponseResultInner isBuyer(@jakarta.annotation.Nullable Boolean isBuyer) {
        this.isBuyer = isBuyer;
        return this;
    }

    /**
     * Get isBuyer
     *
     * @return isBuyer
     */
    @jakarta.annotation.Nullable
    public Boolean getIsBuyer() {
        return isBuyer;
    }

    public void setIsBuyer(@jakarta.annotation.Nullable Boolean isBuyer) {
        this.isBuyer = isBuyer;
    }

    public MyTradesResponseResultInner isMaker(@jakarta.annotation.Nullable Boolean isMaker) {
        this.isMaker = isMaker;
        return this;
    }

    /**
     * Get isMaker
     *
     * @return isMaker
     */
    @jakarta.annotation.Nullable
    public Boolean getIsMaker() {
        return isMaker;
    }

    public void setIsMaker(@jakarta.annotation.Nullable Boolean isMaker) {
        this.isMaker = isMaker;
    }

    public MyTradesResponseResultInner isBestMatch(
            @jakarta.annotation.Nullable Boolean isBestMatch) {
        this.isBestMatch = isBestMatch;
        return this;
    }

    /**
     * Get isBestMatch
     *
     * @return isBestMatch
     */
    @jakarta.annotation.Nullable
    public Boolean getIsBestMatch() {
        return isBestMatch;
    }

    public void setIsBestMatch(@jakarta.annotation.Nullable Boolean isBestMatch) {
        this.isBestMatch = isBestMatch;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        MyTradesResponseResultInner myTradesResponseResultInner = (MyTradesResponseResultInner) o;
        return Objects.equals(this.symbol, myTradesResponseResultInner.symbol)
                && Objects.equals(this.id, myTradesResponseResultInner.id)
                && Objects.equals(this.orderId, myTradesResponseResultInner.orderId)
                && Objects.equals(this.orderListId, myTradesResponseResultInner.orderListId)
                && Objects.equals(this.price, myTradesResponseResultInner.price)
                && Objects.equals(this.qty, myTradesResponseResultInner.qty)
                && Objects.equals(this.quoteQty, myTradesResponseResultInner.quoteQty)
                && Objects.equals(this.commission, myTradesResponseResultInner.commission)
                && Objects.equals(this.commissionAsset, myTradesResponseResultInner.commissionAsset)
                && Objects.equals(this.time, myTradesResponseResultInner.time)
                && Objects.equals(this.isBuyer, myTradesResponseResultInner.isBuyer)
                && Objects.equals(this.isMaker, myTradesResponseResultInner.isMaker)
                && Objects.equals(this.isBestMatch, myTradesResponseResultInner.isBestMatch);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                symbol,
                id,
                orderId,
                orderListId,
                price,
                qty,
                quoteQty,
                commission,
                commissionAsset,
                time,
                isBuyer,
                isMaker,
                isBestMatch);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class MyTradesResponseResultInner {\n");
        sb.append("		symbol: ").append(toIndentedString(symbol)).append("\n");
        sb.append("		id: ").append(toIndentedString(id)).append("\n");
        sb.append("		orderId: ").append(toIndentedString(orderId)).append("\n");
        sb.append("		orderListId: ").append(toIndentedString(orderListId)).append("\n");
        sb.append("		price: ").append(toIndentedString(price)).append("\n");
        sb.append("		qty: ").append(toIndentedString(qty)).append("\n");
        sb.append("		quoteQty: ").append(toIndentedString(quoteQty)).append("\n");
        sb.append("		commission: ").append(toIndentedString(commission)).append("\n");
        sb.append("		commissionAsset: ").append(toIndentedString(commissionAsset)).append("\n");
        sb.append("		time: ").append(toIndentedString(time)).append("\n");
        sb.append("		isBuyer: ").append(toIndentedString(isBuyer)).append("\n");
        sb.append("		isMaker: ").append(toIndentedString(isMaker)).append("\n");
        sb.append("		isBestMatch: ").append(toIndentedString(isBestMatch)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    public String toUrlQueryString() {
        StringBuilder sb = new StringBuilder();
        Map<String, String> valMap = new TreeMap<String, String>();
        valMap.put("apiKey", getApiKey());
        String symbolValue = getSymbol();
        if (symbolValue != null) {
            String symbolValueAsString = symbolValue.toString();
            valMap.put("symbol", symbolValueAsString);
        }
        Long idValue = getId();
        if (idValue != null) {
            String idValueAsString = idValue.toString();
            valMap.put("id", idValueAsString);
        }
        Long orderIdValue = getOrderId();
        if (orderIdValue != null) {
            String orderIdValueAsString = orderIdValue.toString();
            valMap.put("orderId", orderIdValueAsString);
        }
        Long orderListIdValue = getOrderListId();
        if (orderListIdValue != null) {
            String orderListIdValueAsString = orderListIdValue.toString();
            valMap.put("orderListId", orderListIdValueAsString);
        }
        String priceValue = getPrice();
        if (priceValue != null) {
            String priceValueAsString = priceValue.toString();
            valMap.put("price", priceValueAsString);
        }
        String qtyValue = getQty();
        if (qtyValue != null) {
            String qtyValueAsString = qtyValue.toString();
            valMap.put("qty", qtyValueAsString);
        }
        String quoteQtyValue = getQuoteQty();
        if (quoteQtyValue != null) {
            String quoteQtyValueAsString = quoteQtyValue.toString();
            valMap.put("quoteQty", quoteQtyValueAsString);
        }
        String commissionValue = getCommission();
        if (commissionValue != null) {
            String commissionValueAsString = commissionValue.toString();
            valMap.put("commission", commissionValueAsString);
        }
        String commissionAssetValue = getCommissionAsset();
        if (commissionAssetValue != null) {
            String commissionAssetValueAsString = commissionAssetValue.toString();
            valMap.put("commissionAsset", commissionAssetValueAsString);
        }
        Long timeValue = getTime();
        if (timeValue != null) {
            String timeValueAsString = timeValue.toString();
            valMap.put("time", timeValueAsString);
        }
        Boolean isBuyerValue = getIsBuyer();
        if (isBuyerValue != null) {
            String isBuyerValueAsString = isBuyerValue.toString();
            valMap.put("isBuyer", isBuyerValueAsString);
        }
        Boolean isMakerValue = getIsMaker();
        if (isMakerValue != null) {
            String isMakerValueAsString = isMakerValue.toString();
            valMap.put("isMaker", isMakerValueAsString);
        }
        Boolean isBestMatchValue = getIsBestMatch();
        if (isBestMatchValue != null) {
            String isBestMatchValueAsString = isBestMatchValue.toString();
            valMap.put("isBestMatch", isBestMatchValueAsString);
        }

        valMap.put("timestamp", getTimestamp());
        return asciiEncode(
                valMap.keySet().stream()
                        .map(key -> key + "=" + valMap.get(key))
                        .collect(Collectors.joining("&")));
    }

    public Map<String, Object> toMap() {
        Map<String, Object> valMap = new TreeMap<String, Object>();
        valMap.put("apiKey", getApiKey());
        Object symbolValue = getSymbol();
        if (symbolValue != null) {
            valMap.put("symbol", symbolValue);
        }
        Object idValue = getId();
        if (idValue != null) {
            valMap.put("id", idValue);
        }
        Object orderIdValue = getOrderId();
        if (orderIdValue != null) {
            valMap.put("orderId", orderIdValue);
        }
        Object orderListIdValue = getOrderListId();
        if (orderListIdValue != null) {
            valMap.put("orderListId", orderListIdValue);
        }
        Object priceValue = getPrice();
        if (priceValue != null) {
            valMap.put("price", priceValue);
        }
        Object qtyValue = getQty();
        if (qtyValue != null) {
            valMap.put("qty", qtyValue);
        }
        Object quoteQtyValue = getQuoteQty();
        if (quoteQtyValue != null) {
            valMap.put("quoteQty", quoteQtyValue);
        }
        Object commissionValue = getCommission();
        if (commissionValue != null) {
            valMap.put("commission", commissionValue);
        }
        Object commissionAssetValue = getCommissionAsset();
        if (commissionAssetValue != null) {
            valMap.put("commissionAsset", commissionAssetValue);
        }
        Object timeValue = getTime();
        if (timeValue != null) {
            valMap.put("time", timeValue);
        }
        Object isBuyerValue = getIsBuyer();
        if (isBuyerValue != null) {
            valMap.put("isBuyer", isBuyerValue);
        }
        Object isMakerValue = getIsMaker();
        if (isMakerValue != null) {
            valMap.put("isMaker", isMakerValue);
        }
        Object isBestMatchValue = getIsBestMatch();
        if (isBestMatchValue != null) {
            valMap.put("isBestMatch", isBestMatchValue);
        }

        valMap.put("timestamp", getTimestamp());
        return valMap;
    }

    public static String asciiEncode(String s) {
        return new String(s.getBytes(), StandardCharsets.US_ASCII);
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n		");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("symbol");
        openapiFields.add("id");
        openapiFields.add("orderId");
        openapiFields.add("orderListId");
        openapiFields.add("price");
        openapiFields.add("qty");
        openapiFields.add("quoteQty");
        openapiFields.add("commission");
        openapiFields.add("commissionAsset");
        openapiFields.add("time");
        openapiFields.add("isBuyer");
        openapiFields.add("isMaker");
        openapiFields.add("isBestMatch");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to
     *     MyTradesResponseResultInner
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!MyTradesResponseResultInner.openapiRequiredFields
                    .isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(
                        String.format(
                                "The required field(s) %s in MyTradesResponseResultInner is not"
                                        + " found in the empty JSON string",
                                MyTradesResponseResultInner.openapiRequiredFields.toString()));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!MyTradesResponseResultInner.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(
                        String.format(
                                "The field `%s` in the JSON string is not defined in the"
                                        + " `MyTradesResponseResultInner` properties. JSON: %s",
                                entry.getKey(), jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if ((jsonObj.get("symbol") != null && !jsonObj.get("symbol").isJsonNull())
                && !jsonObj.get("symbol").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `symbol` to be a primitive type in the JSON string"
                                    + " but got `%s`",
                            jsonObj.get("symbol").toString()));
        }
        if ((jsonObj.get("price") != null && !jsonObj.get("price").isJsonNull())
                && !jsonObj.get("price").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `price` to be a primitive type in the JSON string"
                                    + " but got `%s`",
                            jsonObj.get("price").toString()));
        }
        if ((jsonObj.get("qty") != null && !jsonObj.get("qty").isJsonNull())
                && !jsonObj.get("qty").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `qty` to be a primitive type in the JSON string but"
                                    + " got `%s`",
                            jsonObj.get("qty").toString()));
        }
        if ((jsonObj.get("quoteQty") != null && !jsonObj.get("quoteQty").isJsonNull())
                && !jsonObj.get("quoteQty").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `quoteQty` to be a primitive type in the JSON"
                                    + " string but got `%s`",
                            jsonObj.get("quoteQty").toString()));
        }
        if ((jsonObj.get("commission") != null && !jsonObj.get("commission").isJsonNull())
                && !jsonObj.get("commission").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `commission` to be a primitive type in the JSON"
                                    + " string but got `%s`",
                            jsonObj.get("commission").toString()));
        }
        if ((jsonObj.get("commissionAsset") != null && !jsonObj.get("commissionAsset").isJsonNull())
                && !jsonObj.get("commissionAsset").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `commissionAsset` to be a primitive type in the"
                                    + " JSON string but got `%s`",
                            jsonObj.get("commissionAsset").toString()));
        }
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!MyTradesResponseResultInner.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'MyTradesResponseResultInner' and its
                // subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<MyTradesResponseResultInner> thisAdapter =
                    gson.getDelegateAdapter(this, TypeToken.get(MyTradesResponseResultInner.class));

            return (TypeAdapter<T>)
                    new TypeAdapter<MyTradesResponseResultInner>() {
                        @Override
                        public void write(JsonWriter out, MyTradesResponseResultInner value)
                                throws IOException {
                            JsonElement obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                            elementAdapter.write(out, obj);
                        }

                        @Override
                        public MyTradesResponseResultInner read(JsonReader in) throws IOException {
                            JsonElement jsonElement = elementAdapter.read(in);
                            // validateJsonElement(jsonElement);
                            return thisAdapter.fromJsonTree(jsonElement);
                        }
                    }.nullSafe();
        }
    }

    /**
     * Create an instance of MyTradesResponseResultInner given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of MyTradesResponseResultInner
     * @throws IOException if the JSON string is invalid with respect to MyTradesResponseResultInner
     */
    public static MyTradesResponseResultInner fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, MyTradesResponseResultInner.class);
    }

    /**
     * Convert an instance of MyTradesResponseResultInner to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
