/*
 * Spot REST API
 * Access market data, manage accounts, and trade on Binance Spot.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.client.spot.rest.api;

import com.binance.connector.client.common.ApiClient;
import com.binance.connector.client.common.ApiException;
import com.binance.connector.client.common.ApiResponse;
import com.binance.connector.client.common.JSON;
import com.binance.connector.client.common.Pair;
import com.binance.connector.client.common.SystemUtil;
import com.binance.connector.client.common.configuration.ClientConfiguration;
import com.binance.connector.client.common.exception.ConstraintViolationException;
import com.binance.connector.client.spot.rest.model.ExchangeInfoResponse;
import com.binance.connector.client.spot.rest.model.ExecutionRulesResponse;
import com.binance.connector.client.spot.rest.model.Permissions;
import com.binance.connector.client.spot.rest.model.SymbolStatus;
import com.binance.connector.client.spot.rest.model.Symbols;
import com.binance.connector.client.spot.rest.model.TimeResponse;
import com.google.gson.reflect.TypeToken;
import jakarta.validation.ConstraintViolation;
import jakarta.validation.Validation;
import jakarta.validation.Validator;
import jakarta.validation.constraints.*;
import jakarta.validation.executable.ExecutableValidator;
import java.lang.reflect.Method;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import org.hibernate.validator.messageinterpolation.ParameterMessageInterpolator;

public class GeneralApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    private static final String USER_AGENT =
            String.format(
                    "binance-spot/11.0.0 (Java/%s; %s; %s)",
                    SystemUtil.getJavaVersion(), SystemUtil.getOs(), SystemUtil.getArch());
    private static final boolean HAS_TIME_UNIT = true;

    public GeneralApi(ClientConfiguration clientConfiguration) {
        this(new ApiClient(clientConfiguration));
    }

    public GeneralApi(ApiClient apiClient) {
        apiClient.setUserAgent(USER_AGENT);
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for exchangeInfo
     *
     * @param symbol Example: curl -X GET
     *     \&quot;https://api.binance.com/api/v3/exchangeInfo?symbol&#x3D;BNBBTC\&quot; (optional)
     * @param symbols Examples: curl -X GET
     *     \&quot;https://api.binance.com/api/v3/exchangeInfo?symbols&#x3D;%5B%22BNBBTC%22,%22BTCUSDT%22%5D\&quot;
     *     or curl -g -X GET
     *     &#39;https://api.binance.com/api/v3/exchangeInfo?symbols&#x3D;[\&quot;BTCUSDT\&quot;,\&quot;BNBBTC\&quot;]&#39;
     *     (optional)
     * @param permissions Examples: curl -X GET
     *     \&quot;https://api.binance.com/api/v3/exchangeInfo?permissions&#x3D;SPOT\&quot; curl -X
     *     GET
     *     \&quot;https://api.binance.com/api/v3/exchangeInfo?permissions&#x3D;%5B%22MARGIN%22%2C%22LEVERAGED%22%5D\&quot;
     *     or curl -g -X GET
     *     &#39;https://api.binance.com/api/v3/exchangeInfo?permissions&#x3D;[\&quot;MARGIN\&quot;,\&quot;LEVERAGED\&quot;]&#39;
     *     (optional)
     * @param showPermissionSets Controls whether the content of the &#x60;permissionSets&#x60;
     *     field is populated or not. (optional)
     * @param symbolStatus Filters for symbols that have this &#x60;tradingStatus&#x60;. Cannot be
     *     used in combination with &#x60;symbols&#x60; or &#x60;symbol&#x60;. (optional)
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     *     <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Exchange information </td><td>  -  </td></tr>
     * </table>
     *
     * @see <a
     *     href="https://developers.binance.com/en/docs/catalog/core-trading-spot-trading/api/rest-api/general#exchange-info">Exchange
     *     information Documentation</a>
     */
    private okhttp3.Call exchangeInfoCall(
            String symbol,
            Symbols symbols,
            Permissions permissions,
            Boolean showPermissionSets,
            SymbolStatus symbolStatus)
            throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {};

        // Determine Base Path to Use
        if (localCustomBaseUrl != null) {
            basePath = localCustomBaseUrl;
        } else if (localBasePaths.length > 0) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v3/exchangeInfo";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (symbol != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("symbol", symbol));
        }

        if (symbols != null) {
            String json = JSON.getGson().toJson(symbols);
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("symbols", json));
        }

        if (permissions != null) {
            String json = JSON.getGson().toJson(permissions);
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("permissions", json));
        }

        if (showPermissionSets != null) {
            localVarQueryParams.addAll(
                    localVarApiClient.parameterToPair("showPermissionSets", showPermissionSets));
        }

        if (symbolStatus != null) {
            localVarQueryParams.addAll(
                    localVarApiClient.parameterToPair("symbolStatus", symbolStatus));
        }

        final String[] localVarAccepts = {"application/json"};
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {"application/x-www-form-urlencoded"};
        final String localVarContentType =
                localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (!localVarFormParams.isEmpty() && localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }
        Set<String> localVarAuthNames = new HashSet<>();
        if (HAS_TIME_UNIT) {
            localVarAuthNames.add("timeUnit");
        }
        return localVarApiClient.buildCall(
                basePath,
                localVarPath,
                "GET",
                localVarQueryParams,
                localVarCollectionQueryParams,
                localVarPostBody,
                localVarHeaderParams,
                localVarCookieParams,
                localVarFormParams,
                localVarAuthNames);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call exchangeInfoValidateBeforeCall(
            String symbol,
            Symbols symbols,
            Permissions permissions,
            Boolean showPermissionSets,
            SymbolStatus symbolStatus)
            throws ApiException {
        try {
            Validator validator =
                    Validation.byDefaultProvider()
                            .configure()
                            .messageInterpolator(new ParameterMessageInterpolator())
                            .buildValidatorFactory()
                            .getValidator();
            ExecutableValidator executableValidator = validator.forExecutables();

            Object[] parameterValues = {
                symbol, symbols, permissions, showPermissionSets, symbolStatus
            };
            Method method =
                    this.getClass()
                            .getMethod(
                                    "exchangeInfo",
                                    String.class,
                                    Symbols.class,
                                    Permissions.class,
                                    Boolean.class,
                                    SymbolStatus.class);
            Set<ConstraintViolation<GeneralApi>> violations =
                    executableValidator.validateParameters(this, method, parameterValues);

            if (violations.size() == 0) {
                return exchangeInfoCall(
                        symbol, symbols, permissions, showPermissionSets, symbolStatus);
            } else {
                throw new ConstraintViolationException((Set) violations);
            }
        } catch (NoSuchMethodException e) {
            e.printStackTrace();
            throw new ApiException(e.getMessage());
        } catch (SecurityException e) {
            e.printStackTrace();
            throw new ApiException(e.getMessage());
        }
    }

    /**
     * Exchange information Current exchange trading rules and symbol information Weight(IP): 20
     * Security Type: NONE Notes: **Data Source:** Memory **Notes:** * If the value provided to
     * &#x60;symbol&#x60; or &#x60;symbols&#x60; do not exist, the endpoint will throw an error
     * saying the symbol is invalid. * All parameters are optional. * &#x60;permissions&#x60; can
     * support single or multiple values (e.g. &#x60;SPOT&#x60;,
     * &#x60;[\&quot;MARGIN\&quot;,\&quot;LEVERAGED\&quot;]&#x60;). This cannot be used in
     * combination with &#x60;symbol&#x60; or &#x60;symbols&#x60;. * If &#x60;permissions&#x60;
     * parameter not provided, all symbols that have either &#x60;SPOT&#x60;, &#x60;MARGIN&#x60;, or
     * &#x60;LEVERAGED&#x60; permission will be exposed. * To display symbols with any permission
     * you need to specify them explicitly in &#x60;permissions&#x60;: (e.g.
     * &#x60;[\&quot;SPOT\&quot;,\&quot;MARGIN\&quot;,...]&#x60;.). See Account and Symbol
     * Permissions for the full list. **Examples of Symbol Permissions Interpretation from the
     * Response:** * &#x60;[[\&quot;A\&quot;,\&quot;B\&quot;]]&#x60; means you may place an order if
     * your account has either permission \&quot;A\&quot; **or** permission \&quot;B\&quot;. *
     * &#x60;[[\&quot;A\&quot;],[\&quot;B\&quot;]]&#x60; means you can place an order if your
     * account has permission \&quot;A\&quot; **and** permission \&quot;B\&quot;. *
     * &#x60;[[\&quot;A\&quot;],[\&quot;B\&quot;,\&quot;C\&quot;]]&#x60; means you can place an
     * order if your account has permission \&quot;A\&quot; **and** permission \&quot;B\&quot; or
     * permission \&quot;C\&quot;. (Inclusive or is applied here, not exclusive or, so your account
     * may have both permission \&quot;B\&quot; and permission \&quot;C\&quot;.)
     *
     * @param symbol Example: curl -X GET
     *     \&quot;https://api.binance.com/api/v3/exchangeInfo?symbol&#x3D;BNBBTC\&quot; (optional)
     * @param symbols Examples: curl -X GET
     *     \&quot;https://api.binance.com/api/v3/exchangeInfo?symbols&#x3D;%5B%22BNBBTC%22,%22BTCUSDT%22%5D\&quot;
     *     or curl -g -X GET
     *     &#39;https://api.binance.com/api/v3/exchangeInfo?symbols&#x3D;[\&quot;BTCUSDT\&quot;,\&quot;BNBBTC\&quot;]&#39;
     *     (optional)
     * @param permissions Examples: curl -X GET
     *     \&quot;https://api.binance.com/api/v3/exchangeInfo?permissions&#x3D;SPOT\&quot; curl -X
     *     GET
     *     \&quot;https://api.binance.com/api/v3/exchangeInfo?permissions&#x3D;%5B%22MARGIN%22%2C%22LEVERAGED%22%5D\&quot;
     *     or curl -g -X GET
     *     &#39;https://api.binance.com/api/v3/exchangeInfo?permissions&#x3D;[\&quot;MARGIN\&quot;,\&quot;LEVERAGED\&quot;]&#39;
     *     (optional)
     * @param showPermissionSets Controls whether the content of the &#x60;permissionSets&#x60;
     *     field is populated or not. (optional)
     * @param symbolStatus Filters for symbols that have this &#x60;tradingStatus&#x60;. Cannot be
     *     used in combination with &#x60;symbols&#x60; or &#x60;symbol&#x60;. (optional)
     * @return ApiResponse&lt;ExchangeInfoResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
     *     response body
     * @http.response.details
     *     <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Exchange information </td><td>  -  </td></tr>
     * </table>
     *
     * @see <a
     *     href="https://developers.binance.com/en/docs/catalog/core-trading-spot-trading/api/rest-api/general#exchange-info">Exchange
     *     information Documentation</a>
     */
    public ApiResponse<ExchangeInfoResponse> exchangeInfo(
            String symbol,
            Symbols symbols,
            Permissions permissions,
            Boolean showPermissionSets,
            SymbolStatus symbolStatus)
            throws ApiException {
        okhttp3.Call localVarCall =
                exchangeInfoValidateBeforeCall(
                        symbol, symbols, permissions, showPermissionSets, symbolStatus);
        java.lang.reflect.Type localVarReturnType =
                new TypeToken<ExchangeInfoResponse>() {}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Build call for executionRules
     *
     * @param symbol Query for specified symbol. (optional)
     * @param symbols Query for multiple symbols. (optional)
     * @param symbolStatus Query for all symbols with the specified status. (optional)
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     *     <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Query execution rules </td><td>  -  </td></tr>
     * </table>
     *
     * @see <a
     *     href="https://developers.binance.com/en/docs/catalog/core-trading-spot-trading/api/rest-api/general#execution-rules">Query
     *     Execution Rules Documentation</a>
     */
    private okhttp3.Call executionRulesCall(
            String symbol, Symbols symbols, SymbolStatus symbolStatus) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {};

        // Determine Base Path to Use
        if (localCustomBaseUrl != null) {
            basePath = localCustomBaseUrl;
        } else if (localBasePaths.length > 0) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v3/executionRules";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (symbol != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("symbol", symbol));
        }

        if (symbols != null) {
            String json = JSON.getGson().toJson(symbols);
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("symbols", json));
        }

        if (symbolStatus != null) {
            localVarQueryParams.addAll(
                    localVarApiClient.parameterToPair("symbolStatus", symbolStatus));
        }

        final String[] localVarAccepts = {"application/json"};
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {"application/x-www-form-urlencoded"};
        final String localVarContentType =
                localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (!localVarFormParams.isEmpty() && localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }
        Set<String> localVarAuthNames = new HashSet<>();
        if (HAS_TIME_UNIT) {
            localVarAuthNames.add("timeUnit");
        }
        return localVarApiClient.buildCall(
                basePath,
                localVarPath,
                "GET",
                localVarQueryParams,
                localVarCollectionQueryParams,
                localVarPostBody,
                localVarHeaderParams,
                localVarCookieParams,
                localVarFormParams,
                localVarAuthNames);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call executionRulesValidateBeforeCall(
            String symbol, Symbols symbols, SymbolStatus symbolStatus) throws ApiException {
        try {
            Validator validator =
                    Validation.byDefaultProvider()
                            .configure()
                            .messageInterpolator(new ParameterMessageInterpolator())
                            .buildValidatorFactory()
                            .getValidator();
            ExecutableValidator executableValidator = validator.forExecutables();

            Object[] parameterValues = {symbol, symbols, symbolStatus};
            Method method =
                    this.getClass()
                            .getMethod(
                                    "executionRules",
                                    String.class,
                                    Symbols.class,
                                    SymbolStatus.class);
            Set<ConstraintViolation<GeneralApi>> violations =
                    executableValidator.validateParameters(this, method, parameterValues);

            if (violations.size() == 0) {
                return executionRulesCall(symbol, symbols, symbolStatus);
            } else {
                throw new ConstraintViolationException((Set) violations);
            }
        } catch (NoSuchMethodException e) {
            e.printStackTrace();
            throw new ApiException(e.getMessage());
        } catch (SecurityException e) {
            e.printStackTrace();
            throw new ApiException(e.getMessage());
        }
    }

    /**
     * Query Execution Rules Query execution rules for symbols. Weight: Parameter | Weight --- | ---
     * &#x60;symbol&#x60; | 2 &#x60;symbols&#x60; | 2 for each &#x60;symbol&#x60;, capped at a max
     * of 40 &#x60;symbolStatus&#x60; | 40 None | 40 Security Type: NONE Notes: **Data Source:**
     * Memory **Note:**: No combination of multiple parameters is allowed.
     *
     * @param symbol Query for specified symbol. (optional)
     * @param symbols Query for multiple symbols. (optional)
     * @param symbolStatus Query for all symbols with the specified status. (optional)
     * @return ApiResponse&lt;ExecutionRulesResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
     *     response body
     * @http.response.details
     *     <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Query execution rules </td><td>  -  </td></tr>
     * </table>
     *
     * @see <a
     *     href="https://developers.binance.com/en/docs/catalog/core-trading-spot-trading/api/rest-api/general#execution-rules">Query
     *     Execution Rules Documentation</a>
     */
    public ApiResponse<ExecutionRulesResponse> executionRules(
            String symbol, Symbols symbols, SymbolStatus symbolStatus) throws ApiException {
        okhttp3.Call localVarCall = executionRulesValidateBeforeCall(symbol, symbols, symbolStatus);
        java.lang.reflect.Type localVarReturnType =
                new TypeToken<ExecutionRulesResponse>() {}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Build call for ping
     *
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     *     <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     * </table>
     *
     * @see <a
     *     href="https://developers.binance.com/en/docs/catalog/core-trading-spot-trading/api/rest-api/general#ping">Test
     *     connectivity Documentation</a>
     */
    private okhttp3.Call pingCall() throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {};

        // Determine Base Path to Use
        if (localCustomBaseUrl != null) {
            basePath = localCustomBaseUrl;
        } else if (localBasePaths.length > 0) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v3/ping";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {"application/json"};
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {"application/x-www-form-urlencoded"};
        final String localVarContentType =
                localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (!localVarFormParams.isEmpty() && localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }
        Set<String> localVarAuthNames = new HashSet<>();
        if (HAS_TIME_UNIT) {
            localVarAuthNames.add("timeUnit");
        }
        return localVarApiClient.buildCall(
                basePath,
                localVarPath,
                "GET",
                localVarQueryParams,
                localVarCollectionQueryParams,
                localVarPostBody,
                localVarHeaderParams,
                localVarCookieParams,
                localVarFormParams,
                localVarAuthNames);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call pingValidateBeforeCall() throws ApiException {
        try {
            Validator validator =
                    Validation.byDefaultProvider()
                            .configure()
                            .messageInterpolator(new ParameterMessageInterpolator())
                            .buildValidatorFactory()
                            .getValidator();
            ExecutableValidator executableValidator = validator.forExecutables();

            Object[] parameterValues = {};
            Method method = this.getClass().getMethod("ping");
            Set<ConstraintViolation<GeneralApi>> violations =
                    executableValidator.validateParameters(this, method, parameterValues);

            if (violations.size() == 0) {
                return pingCall();
            } else {
                throw new ConstraintViolationException((Set) violations);
            }
        } catch (NoSuchMethodException e) {
            e.printStackTrace();
            throw new ApiException(e.getMessage());
        } catch (SecurityException e) {
            e.printStackTrace();
            throw new ApiException(e.getMessage());
        }
    }

    /**
     * Test connectivity Test connectivity to the Rest API. Weight(IP): 1 Security Type: NONE
     *
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
     *     response body
     * @http.response.details
     *     <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     * </table>
     *
     * @see <a
     *     href="https://developers.binance.com/en/docs/catalog/core-trading-spot-trading/api/rest-api/general#ping">Test
     *     connectivity Documentation</a>
     */
    public ApiResponse<Void> ping() throws ApiException {
        okhttp3.Call localVarCall = pingValidateBeforeCall();
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Build call for time
     *
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     *     <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Check server time </td><td>  -  </td></tr>
     * </table>
     *
     * @see <a
     *     href="https://developers.binance.com/en/docs/catalog/core-trading-spot-trading/api/rest-api/general#time">Check
     *     server time Documentation</a>
     */
    private okhttp3.Call timeCall() throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {};

        // Determine Base Path to Use
        if (localCustomBaseUrl != null) {
            basePath = localCustomBaseUrl;
        } else if (localBasePaths.length > 0) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v3/time";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {"application/json"};
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {"application/x-www-form-urlencoded"};
        final String localVarContentType =
                localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (!localVarFormParams.isEmpty() && localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }
        Set<String> localVarAuthNames = new HashSet<>();
        if (HAS_TIME_UNIT) {
            localVarAuthNames.add("timeUnit");
        }
        return localVarApiClient.buildCall(
                basePath,
                localVarPath,
                "GET",
                localVarQueryParams,
                localVarCollectionQueryParams,
                localVarPostBody,
                localVarHeaderParams,
                localVarCookieParams,
                localVarFormParams,
                localVarAuthNames);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call timeValidateBeforeCall() throws ApiException {
        try {
            Validator validator =
                    Validation.byDefaultProvider()
                            .configure()
                            .messageInterpolator(new ParameterMessageInterpolator())
                            .buildValidatorFactory()
                            .getValidator();
            ExecutableValidator executableValidator = validator.forExecutables();

            Object[] parameterValues = {};
            Method method = this.getClass().getMethod("time");
            Set<ConstraintViolation<GeneralApi>> violations =
                    executableValidator.validateParameters(this, method, parameterValues);

            if (violations.size() == 0) {
                return timeCall();
            } else {
                throw new ConstraintViolationException((Set) violations);
            }
        } catch (NoSuchMethodException e) {
            e.printStackTrace();
            throw new ApiException(e.getMessage());
        } catch (SecurityException e) {
            e.printStackTrace();
            throw new ApiException(e.getMessage());
        }
    }

    /**
     * Check server time Test connectivity to the Rest API and get the current server time.
     * Weight(IP): 1 Security Type: NONE
     *
     * @return ApiResponse&lt;TimeResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
     *     response body
     * @http.response.details
     *     <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Check server time </td><td>  -  </td></tr>
     * </table>
     *
     * @see <a
     *     href="https://developers.binance.com/en/docs/catalog/core-trading-spot-trading/api/rest-api/general#time">Check
     *     server time Documentation</a>
     */
    public ApiResponse<TimeResponse> time() throws ApiException {
        okhttp3.Call localVarCall = timeValidateBeforeCall();
        java.lang.reflect.Type localVarReturnType = new TypeToken<TimeResponse>() {}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }
}
